/* Original teaching content. Shared by the page and the executable curriculum audit. */
(function (root) {
'use strict';
const datasets = {
 candy: {name:'Candy shop', columns:{candy:['Gummy Bear','Choco Pop','Mint Bite','Berry Loop','Cocoa Cube','Lemon Drop'],flavour:['fruity','chocolate','mint','fruity','chocolate','fruity'],price:[1.2,2.1,1.5,2.8,3.4,1.8],rating:[4.1,4.6,3.8,4.4,4.9,4.0],shelf:['A','B','A','B','A','B']},a:'price',b:'rating',c:'flavour',d:'shelf',id:'candy'},
 cafe: {name:'Café orders',columns:{drink:['Latte','Tea','Mocha','Espresso','Latte','Tea'],size:['Large','Small','Large','Small','Small','Large'],price:[6.2,3.1,6.8,2.5,4.8,4.2],tip:[1,.5,1.5,.2,.8,.6],shift:['AM','AM','PM','PM','AM','PM']},a:'price',b:'tip',c:'size',d:'shift',id:'drink'},
 pets: {name:'Pet adoption',columns:{name:['Milo','Pepper','Luna','Bean','Rex','Nori'],species:['Cat','Dog','Cat','Rabbit','Dog','Rabbit'],age:[3,7,2,4,5,1],weight:[4.2,18.5,3.6,2.4,22,1.8],room:['A','B','A','B','A','B']},a:'age',b:'weight',c:'species',d:'room',id:'name'},
 students: {name:'Study club',columns:{student:['Ari','Bo','Cy','Dee','Eli','Flo','Gus','Han'],club:['Art','Code','Art','Code','Art','Code','Art','Code'],hours:[1,3,2,4,5,3,6,2],score:[52,71,65,82,89,76,93,61],group:['A','A','B','B','A','A','B','B']},a:'hours',b:'score',c:'club',d:'group',id:'student'},
 games: {name:'Board games',columns:{game:['Orbit','Tiles','Quest','Grove','Castle','Cards'],genre:['Strategy','Puzzle','Adventure','Strategy','Adventure','Puzzle'],minutes:[20,15,60,35,45,10],rating:[4.1,3.8,4.7,4.4,4.5,3.6],players:['Two','Solo','Two','Solo','Two','Solo']},a:'minutes',b:'rating',c:'genre',d:'players',id:'game'},
 weather: {name:'Weather diary',columns:{day:['Mon','Tue','Wed','Thu','Fri','Sat','Sun','Mon'],sky:['Sun','Rain','Sun','Cloud','Rain','Sun','Cloud','Sun'],temperature:[28,24,30,27,23,31,26,29],humidity:[62,89,60,74,92,58,78,65],station:['East','East','West','West','East','East','West','West']},a:'temperature',b:'humidity',c:'sky',d:'station',id:'day'},
 movies: {name:'Movie night',columns:{movie:['Moon','River','Spark','Stone','Map','Cloud'],genre:['Drama','Comedy','Drama','Action','Comedy','Action'],minutes:[90,105,112,98,85,120],rating:[3.7,4.2,4.8,4.0,3.9,4.5],screen:['One','One','Two','Two','One','Two']},a:'minutes',b:'rating',c:'genre',d:'screen',id:'movie'},
 messy: {name:'Messy café orders', columns:{order:[101,102,103,104,104,105,106,107],drink:[' latte ','TEA',' mocha ','Latte','Latte','tea ','ESPRESSO',' mocha'],size:['LARGE','small','LARGE','Small','Small','SMALL','small','large'],price:['6.20','3.10','oops',null,null,'4.20','2.50','6.80'],tip:[1,.5,null,.8,.8,.6,.2,1.5],date:['2026-06-01','2026-06-02','not a date','2026-06-04','2026-06-04','2026-06-05','2026-06-06','2026-06-07']},a:'tip',b:'order',c:'size',d:'drink',id:'order'},
 messy_games: {name:'Messy game sales',columns:{order:[201,202,203,204,204,205],drink:[' orbit ','TILES','quest ','Grove','Grove',' cards'],size:['BOX','small','BOX','Small','Small','SMALL'],price:['20','15',null,'bad','bad','10'],tip:[2,null,4,3,3,1],date:['2026-07-01','2026-07-02','bad','2026-07-04','2026-07-04','2026-07-06']},a:'tip',b:'order',c:'size',d:'drink',id:'order'},
 messy_pets: {name:'Messy pet supplies',columns:{order:[301,302,303,304,304,305],drink:[' hay ','FOOD',' toy ','Bowl','Bowl',' food '],size:['LARGE','small','LARGE','Small','Small','SMALL'],price:['8.50','12','bad',null,null,'6'],tip:[1,2,null,.5,.5,1.5],date:['2026-08-01','2026-08-02','invalid','2026-08-04','2026-08-04','2026-08-06']},a:'tip',b:'order',c:'size',d:'drink',id:'order'}
};
const decks=[
 {id:'inspect',number:'01',title:'Inspect',tagline:'Understand what arrived.',description:'Meet a table, find your way around it, and ask your first useful questions.',chapters:['Getting oriented','Selecting data','Understanding values','Reading the whole table']},
 {id:'wrangle',number:'02',title:'Wrangle / Preprocess',tagline:'Make messy data usable.',description:'Protect the original. Clean, reshape and combine with a reason for every change.',chapters:['A safe working copy','New columns & clean text','Types, dates & missingness','Groups & reshaping','Combining & preparing','A responsible finish']},
 {id:'visualise',number:'03',title:'Visualise',tagline:'Give your questions a picture.',description:'Choose a chart, build it with confidence, and make the meaning clear.',chapters:['The chart canvas','Distributions & estimates','Comparing categories','Relationships','Chart craft','Figures & visual judgement']}
];
const lessons=[];
const py=v=>JSON.stringify(v).replace(/\bnull\b/g,'None');
function setupCode(key){return 'import pandas as pd\n\ndata = '+Object.entries(datasets[key].columns).map(([k,v],i)=>`${i?'    ':'{\n    '}${py(k)}: ${py(v)}`).join(',\n')+'\n}\n\ndf = pd.DataFrame(data)';}
function fill(s,d,r){const values={a:d.a,b:d.b,c:d.c,d:d.d,id:d.id,cat:d.columns[d.c][0],n:[2,3,4][r],threshold:d.columns[d.a][1],name:d.name};return s.replace(/\{(a|b|c|d|id|cat|n|threshold|name)\}/g,(_,k)=>values[k]);}
function add(id,title,chapter,goal,explanation,syntax,task,solution,options={}){
 const deck=id[0]==='I'?'inspect':id[0]==='W'?'wrangle':'visualise';
 const keys=options.datasets||['candy','cafe','pets'];
 const lesson={id,deck,title,chapter,goal,explanation,syntax:syntax.split('|').map(x=>x.split(' → ')),minutes:options.minutes||8,review:false,rounds:[]};
 keys.forEach((key,r)=>{
  const d=datasets[key],sol=fill(Array.isArray(solution)?solution[r]:solution,d,r);
  const prompt=fill(Array.isArray(task)?task[r]:task,d,r);
  lesson.rounds.push({id:`${id}-${r+1}`,label:['Follow','Change','Transfer'][r],dataset:key,task:prompt,solution:sol,
   starter:r===0?(options.starter?fill(options.starter,d,r):sol.split('\n').map((s,i,a)=>i===a.length-1?'# Complete the last step\n'+s.replace(/\w+(?=\()/,'____'):s).join('\n')):r===1?'# '+prompt+'\n':'# Your Python\n',
   hint:fill(options.hint||'Read the worked example one piece at a time. '+syntax.split('|').map(s=>s.split(' → ')[0]).join(', ')+' are the tools to try.',d,r),
   setup:fill(options.setup||'',d,r),target:options.target||'value',strictDtype:options.strictDtype||false,
   requiredCalls:options.requiredCalls||[],plot:options.plot||null,
   checks:options.checks||null});
 });
 lesson.example=options.example||lesson.rounds[0].solution;
 if(options.stretch)lesson.stretch=options.stretch;
 lessons.push(lesson);return lesson;
}
add('I01','Meet a DataFrame',0,'Build a small table from named columns.','A DataFrame is a table: each row is one observation, each column one kind of information. A variable is a name for a value. The equals sign stores the value on its right under the name on its left. Each list must have the same number of items.','import pandas as pd → load pandas and give it the short name pd|data = → save our dictionary under the name data|{ } → a dictionary pairs column names with their values|[ ] → a list holds the values of one column in row order|"price" → quotes make text; numbers such as 1.2 need no quotes|pd.DataFrame(data) → turn that dictionary into a table|df = → store the table under the name df','Create df with every column and row in the given table. The dictionary data is supplied; import pandas as pd and turn data into a DataFrame.','import pandas as pd\n\ndf = pd.DataFrame(data)\ndf',{target:'df',starter:'import pandas as pd\n\ndf = pd.____(data)\ndf',hint:'DataFrame uses a capital D and F. The dictionary data already holds the visible table.',stretch:'Try changing one number inside a list in the setup example. Why must every list have the same length?'});
add('I02','Take the first look',0,'Look at a few rows before making assumptions.','Writing df on its own displays the table. head() returns the first five rows by default; tail() returns the last five. A number inside the parentheses changes how many. sample(2, random_state=1) chooses two rows reproducibly rather than taking the first two.','df → our table|. → access a tool belonging to the table|head → the tool for first rows|(2) → call it and ask for two rows','Return the first {n} rows of the {name} table.','df.head({n})',{starter:'df.____({n})',stretch:'Try df.tail(2), df.sample(2, random_state=1), and df.head() separately. A sample is not necessarily representative.'});
add('I03','How big is it?',0,'Read the row and column counts.','shape is an attribute: it describes the table without calling a tool, so it has no parentheses. It returns a tuple, an ordered pair (rows, columns). len(df) counts rows only.','df.shape → a pair of counts: rows then columns|len(df) → count the rows|[0] → take the first item; Python starts counting at zero','Return the pair (number of rows, number of columns) for {name}.','df.shape',{starter:'df.____',stretch:'Compare len(df) with df.shape[0]. They should agree.'});
add('I04','What columns arrived?',0,'Find the exact column and row labels.','Column names are case-sensitive: price and Price are different. df.columns holds column labels; df.index holds row labels. An index often starts at zero, but labels need not be consecutive numbers.','df.columns → column labels in order|df.index → row labels in order|list(...) → turn an Index into a familiar Python list','Return the column labels of {name} in their original order as a list.','list(df.columns)',{stretch:'Run list(df.index). After filtering, would you expect those labels to be renumbered automatically?'});
add('I05','What types are these?',0,'Distinguish numeric columns from text.','A dtype is the kind of value stored in a column. int64 holds whole numbers; float64 holds decimals and may include missing values; object often holds text in this pandas version. info() prints column types and non-null counts, and returns None. dtypes returns a Series you can inspect.','df.dtypes → a type for each column|df.info() → print a compact table summary|non-null → a value is present; it is not a guarantee of correctness','Run df.info() to read the overview, then return df.dtypes.','df.info()\ndf.dtypes');
add('I06','Pick one column',1,'Select one named column as a Series.','A Series is one labelled column. One pair of square brackets around a column name selects that Series. The name must be text, inside matching quotes. The row index stays attached.','df["price"] → select one column|[ ] → choose part of a table|Series → one dimension of labelled values','Return the {a} column as a Series.','df["{a}"]',{starter:'df["____"]'});
add('I07','Pick several columns',1,'Keep a two-dimensional table of selected columns.','The outer brackets select from df; the inner brackets create a list of names. Even a list with one name returns a DataFrame. The order in the list becomes the output column order.','df[["price", "rating"]] → a DataFrame with two columns|inner [ ] → a list of column names|comma → separate items in the list','Return a DataFrame containing {b}, then {a}, in that order.','df[["{b}", "{a}"]]',{starter:'df[["{b}", "____"]]'});
add('I08','Rows by position',1,'Select rows using their zero-based positions.','iloc selects by position, regardless of row labels. In a slice start:stop, start is included and stop is excluded. :3 means positions 0, 1 and 2. A comma separates the row selection from the column selection.','df.iloc[:3] → the first three row positions|df.iloc[0] → one row as a Series|df.iloc[:3, :2] → first three rows and first two columns','Use iloc to return the first {n} rows and first two columns.','df.iloc[:{n}, :2]',{requiredCalls:[],hint:'This syntax lesson uses iloc. Both slice stops are excluded.'});
add('I09','Rows and columns by label',1,'Select named rows and columns with loc.','loc uses labels. With the default index the labels happen to be numbers, but loc is not positional. A label slice includes both endpoints; a positional iloc slice excludes its stop.','df.loc[0:2, ["price"]] → labels 0 through 2, and a one-column DataFrame|comma → rows on the left, columns on the right','Return rows labelled 1 through {n}, inclusive, keeping only {a} and {b}.','df.loc[1:{n}, ["{a}", "{b}"]]');
add('I10','Filter rows',1,'Keep rows where a condition is true.','A comparison against a Series creates one True or False for each row: a Boolean mask. Putting that mask inside df[...] keeps the True rows. > means strictly greater than, so equality does not pass.','df["price"] > 2 → one Boolean per row|df[mask] → keep rows where mask is True|== → compare values; = assigns a value','Keep every row where {a} is greater than {threshold}.','df[df["{a}"] > {threshold}]',{starter:'mask = df["{a}"] > ____\ndf[mask]'});
add('I11','Combine conditions',1,'Combine row tests without losing their meaning.','Use & for both, | for either, and ~ to invert a mask. Put each comparison in parentheses. Python and/or work on single truth values; pandas masks need & and |.','(test1) & (test2) → both must be true|test1 OR test2 → at least one must be true|~(test) → reverse True and False','Keep rows where {a} is greater than {threshold} AND {c} equals "{cat}".','df[(df["{a}"] > {threshold}) & (df["{c}"] == "{cat}")]',{stretch:'Replace & with |, then try ~(df["{c}"] == "{cat}"). Predict which rows return first.'});
add('I12','Sort the table',2,'Order filtered rows to answer a question.','sort_values returns a sorted table; it does not change df unless you assign it back. ascending=False puts the largest values first. Sorting reorders whole rows, preserving the relationship between their columns.','sort_values("rating") → sort by that column|ascending=False → largest first|filtered = → give an intermediate table a useful name','Keep rows with {a} greater than {threshold}; then sort them from highest to lowest {b}.','filtered = df[df["{a}"] > {threshold}]\nfiltered.sort_values("{b}", ascending=False)');
add('I13','Find extremes',2,'Ask for the largest or smallest observations.','nlargest(n, column) returns the n rows with the highest values. nsmallest does the opposite. These are concise alternatives to sorting followed by head. Ties can affect which rows are retained.','df.nlargest(2, "price") → two highest-price rows|df.nsmallest(2, "price") → two lowest-price rows','Return the {n} rows with the largest {a}, highest first.','df.nlargest({n}, "{a}")',{stretch:'Find the two smallest instead. Compare with sort_values(...).head(2).'});
add('I14','What values exist?',2,'Find distinct category values.','unique() returns the distinct values in order of appearance. nunique() counts distinct non-missing values by default. These answer different questions: which values, versus how many.','df["flavour"].unique() → distinct values|.nunique() → their count, excluding missing values by default','Return the number of distinct non-missing values in {c}.','df["{c}"].nunique()',{stretch:'Run unique() too. How many items are in the result?'});
add('I15','Count categories',2,'Compare category frequencies and proportions.','value_counts() counts observations per value, usually largest count first. normalize=True divides by the non-missing total, so proportions sum to one. Multiply by 100 for percentages. Missing values are excluded unless dropna=False.','value_counts() → counts per category|normalize=True → fractions rather than counts|dropna=False → also count missing values','Return the proportion of observations in each {c} category.','df["{c}"].value_counts(normalize=True)');
add('I16','Find missing values',2,'Locate gaps before summarising.','isna() produces a Boolean table showing where values are missing. sum() down each column counts True as 1 and False as 0. Missing does not mean zero: a missing tip could be unknown, not no tip.','df.isna() → True at missing cells|.sum() → add down each column|None / NaN → missing-value representations','Return the number of missing values in every column.','df.isna().sum()',{datasets:['messy','messy_games','messy_pets']});
add('I17','Find duplicate rows',2,'Count repeated records without removing anything.','duplicated() marks later copies of an identical row True, leaving the first occurrence False. Its sum counts extra copies. Repeated categories alone do not make duplicate records. Use subset to define a business key only when that key should be unique.','df.duplicated() → a Boolean per row|.sum() → count extra copies|keep=False → mark every member of duplicate groups','Return the number of extra, exactly duplicated rows.','df.duplicated().sum()',{datasets:['messy','messy_games','messy_pets']});
add('I18','Describe numeric columns',3,'Read a compact numerical profile.','describe() reports count, mean, standard deviation, min, 25%, 50%, 75% and max. The 50% row is the median. Count excludes missing values. A large maximum relative to the median invites investigation; it is not permission to delete a row.','df.describe() → summary rows for numeric columns|50% → median, with half the values at or below it|std → spread around the mean','Return describe() for the numeric columns {a} and {b}, in that order.','df[["{a}", "{b}"]].describe()');
add('I19','Summarise groups',3,'Compare a simple average across categories.','groupby splits the rows into groups; agg combines each group into a smaller summary. The result has one row per group. A mean hides variation and does not show group size, so inspect counts too.','groupby("flavour") → gather equal labels|["price"] → choose the measured column|agg("mean") → one average for each group','Return mean {a} for each {c} category as a Series.','df.groupby("{c}")["{a}"].agg("mean")');
add('I20','Compare categories',3,'Count combinations of two categories.','A crosstab counts how often pairs of category values occur. Rows belong to the first Series and columns to the second. Each cell is a count, not an average. A zero means no rows had that combination.','pd.crosstab(first, second) → a two-way frequency table|first → categories on rows|second → categories on columns','Return a crosstab of {c} rows against {d} columns.','pd.crosstab(df["{c}"], df["{d}"])');
add('I21','Inspect numeric relationships',3,'Read correlation as association, not causation.','Correlation measures the strength and direction of a linear relationship. It ranges from −1 to 1 when defined. Values near zero do not rule out curved relationships. Correlation does not establish causation; confounding and tiny samples can mislead.','df.corr(numeric_only=True) → correlations among numeric columns|numeric_only=True → leave text columns out|diagonal → a varying column correlates 1 with itself','Return the correlation matrix for all numeric columns in {name}.','df.corr(numeric_only=True)',{datasets:['students','weather','games']});
add('W01','Protect the original',0,'Make changes on a separate working copy.','clean = df only gives the same table another name. clean = df.copy() creates a separate table, so edits to clean leave df unchanged. Keep that habit when you return to the Playground.','clean = → name for the working table|df.copy() → make a separate DataFrame|clean["price"] = → replace a column in the copy','Make a separate copy named clean. Double its {a} values and leave df unchanged. Display clean.','clean = df.copy()\nclean["{a}"] = clean["{a}"] * 2\nclean',{target:'copy',starter:'clean = df.____()\nclean["{a}"] = clean["{a}"] * 2\nclean'});
add('W02','Rename columns',0,'Give a column a clear name.','rename(columns={old: new}) returns a table with revised labels. The dictionary maps each old name to its new name. Assign the returned table back to df to keep the change. Other columns stay as they were.','columns={"price": "cost"} → map old label to new label|df = df.rename(...) → save the renamed table','Rename {a} to amount in df; keep every other column and row.','df = df.rename(columns={"{a}": "amount"})\ndf',{target:'df'});
add('W03','Keep / reorder columns',0,'Choose a deliberate column order.','Selecting a list of column names returns only those columns, in the order requested. Assigning that table to df deliberately narrows your working table. Inspect the columns before discarding anything.','["name", "weight"] → ordered list of labels|df = df[columns] → keep only the selected columns','Keep only {id}, {b} and {a}, in that order, in df.','df = df[["{id}", "{b}", "{a}"]]\ndf',{target:'df'});
add('W04','Drop columns',0,'Remove an explicitly unwanted field.','drop(columns=[...]) removes columns by name. Without columns=, drop targets row labels by default. Avoid dropping fields simply because you do not understand them; first find their meaning.','drop(columns=["shelf"]) → remove the named column|columns= → make the direction explicit','Remove the {d} column from df and preserve every row.','df = df.drop(columns=["{d}"])\ndf',{target:'df'});
add('W05','Filter unwanted rows',0,'Keep observations using a clear rule.','Filtering is selection, not a judgement about data quality. State a reason before excluding rows. The comparison makes a mask; assigning the filtered table to df keeps the selected observations.','df["price"] >= 2 → include the boundary value|df[mask] → select matching rows','For a report limited to {c} equal to "{cat}", keep just those rows in df.','df = df[df["{c}"] == "{cat}"]\ndf',{target:'df'});
add('W06','Sort and reset',0,'Sort records and give the result a simple index.','After sorting, old row labels travel with their rows. reset_index(drop=True) replaces them with 0, 1, 2… and discards the old labels. Without drop=True the old labels become a new column.','sort_values("price") → order smallest to largest|reset_index(drop=True) → a fresh consecutive index|. → chain the next operation on the returned table','Sort df by {a}, smallest first, then reset its index without adding a column.','df = df.sort_values("{a}").reset_index(drop=True)\ndf',{target:'df'});
add('W07','Create a numeric column',1,'Calculate a whole column at once.','Arithmetic on a Series acts on every row. This is vectorised calculation: no loop is needed. A new label on the left of = creates a column. Existing columns remain available.','df["total"] = → create or replace total|df["price"] * 2 → multiply each value by two','Add a column named doubled equal to {a} multiplied by 2. Preserve all original columns.','df["doubled"] = df["{a}"] * 2\ndf',{target:'df'});
add('W08','Create a conditional column',1,'Choose values using a Boolean rule.','np.where(condition, yes, no) chooses one value for True rows and another for False rows. For several cases, np.select([test1, test2], [value1, value2], default=value3) takes the first matching case. Put more specific cases first.','import numpy as np → load NumPy under a short name|np.where(test, "high", "low") → one result per row|> → the threshold itself belongs to low','Add band: "high" when {a} exceeds {threshold}, otherwise "low".','import numpy as np\ndf["band"] = np.where(df["{a}"] > {threshold}, "high", "low")\ndf',{target:'df',stretch:'Use np.select to add three bands. Choose non-overlapping rules and an explicit default.'});
add('W09','Recode categories',1,'Map known labels and preserve unknown ones deliberately.','replace changes the specified values and leaves all others intact. map uses a lookup dictionary; unmapped values become missing. Decide which behaviour you need before recoding.','replace({"old": "new"}) → preserve other values|map({"old": "new"}) → unknown values become missing','In {c}, replace "{cat}" with "Featured" and keep all other values unchanged.','df["{c}"] = df["{c}"].replace({"{cat}": "Featured"})\ndf',{target:'df',stretch:'Try map with the same dictionary. Use isna().sum() to see the difference.'});
add('W10','Clean text',1,'Remove accidental spaces and inconsistent letter case.','The .str accessor applies string methods to a whole Series. strip() removes spaces at the ends; lower() makes letters lowercase; title() capitalises words. None of these fixes misspellings.','df["drink"].str → string tools for a column|strip() → trim both ends|lower() → lowercase text|title() → title case for display','Clean drink by trimming spaces and making it lowercase. Clean size by trimming spaces and making it title case.','df["drink"] = df["drink"].str.strip().str.lower()\ndf["size"] = df["size"].str.strip().str.title()\ndf',{datasets:['messy','messy_games','messy_pets'],target:'df'});
add('W11','Search / extract text',1,'Select text matches and split structured names.','str.contains tests whether text contains a pattern. regex=False treats it as literal text, and na=False keeps missing entries from making an unusable mask. str.extract(r"(pattern)") uses a capture group to pull matching text; str.split separates text at a delimiter.','str.contains("a", case=False, na=False, regex=False) → literal a, ignoring case|str.extract(r"(\\d+)") → capture one or more digits|str.split("-").str[0] → first piece before a dash','Keep rows whose {id} contains the letter "a", ignoring case. Return the filtered DataFrame.','df[df["{id}"].str.contains("a", case=False, na=False, regex=False)]',{datasets:['candy','cafe','pets'],stretch:'Create a Series with ["A-12", "B-35", "C-8", "A-20"]. Try str.split("-").str[0] and str.extract(r"(\\d+)").'});
add('W12','Convert numeric text',2,'Turn numeric-looking strings into usable numbers.','A quoted number is still text. pd.to_numeric converts it. errors="coerce" makes invalid entries missing instead of crashing. Count those new gaps and investigate; coercion does not fix the original value.','pd.to_numeric(series, errors="coerce") → parse numbers, invalid becomes NaN|"6.20" → text|6.20 → numeric value','Convert price to numeric in df, making invalid text missing. Preserve every row.','df["price"] = pd.to_numeric(df["price"], errors="coerce")\ndf',{datasets:['messy','messy_games','messy_pets'],target:'df',strictDtype:true});
add('W13','Convert data types',2,'Choose a type that fits the values.','astype converts to a named dtype. A string type preserves text meaning, while category stores a fixed set of labels efficiently. Converting decimals to int loses the fractional part; inspect before converting. Nullable Int64, with a capital I, can hold whole numbers and missing values.','astype("category") → store category labels|astype("string") → pandas text type|astype("Int64") → nullable whole numbers','Convert {c} to the category dtype without changing its values.','df["{c}"] = df["{c}"].astype("category")\ndf',{target:'df',strictDtype:true});
add('W14','Parse dates',2,'Convert date text and handle invalid dates visibly.','pd.to_datetime turns text into datetime values. An explicit format avoids guessing month/day order. errors="coerce" produces NaT for invalid dates. NaT is the date equivalent of a missing numeric value.','format="%Y-%m-%d" → four-digit year, month, day|errors="coerce" → invalid date becomes NaT','Parse date using year-month-day order. Keep invalid dates as NaT and retain all rows.','df["date"] = pd.to_datetime(df["date"], format="%Y-%m-%d", errors="coerce")\ndf',{datasets:['messy','messy_games','messy_pets'],target:'df',strictDtype:true});
add('W15','Work with dates',2,'Extract useful calendar features from parsed dates.','The .dt accessor works on datetime Series. year and month are attributes with no parentheses; day_name() is a method call. Parse strings first. Missing dates stay missing in derived columns.','df["date"].dt.year → calendar year|.dt.month → month number|.dt.day_name() → weekday name','Parse date, then add year, month and weekday columns. Retain invalid dates as missing.','df["date"] = pd.to_datetime(df["date"], format="%Y-%m-%d", errors="coerce")\ndf["year"] = df["date"].dt.year\ndf["month"] = df["date"].dt.month\ndf["weekday"] = df["date"].dt.day_name()\ndf',{datasets:['messy','messy_games','messy_pets'],target:'df'});
add('W16','Drop missing rows',2,'Exclude only rows missing a required field.','dropna() with no subset drops any row with any missing cell. That can discard useful data for unrelated reasons. subset names the fields required for this question. Document how many rows are removed and whether their absence could bias the result.','dropna(subset=["price"]) → require a known price|subset= → consider only these columns','Convert price to numeric, then keep only rows with a known numeric price. Do not require a known tip or date.','df["price"] = pd.to_numeric(df["price"], errors="coerce")\ndf = df.dropna(subset=["price"])\ndf',{datasets:['messy','messy_games','messy_pets'],target:'df'});
add('W17','Fill missing values',2,'Choose and document an imputation rule.','fillna fills gaps without changing known values. Here the exercise explicitly chooses the observed median as a temporary estimate, not a recovered fact. Zero is defensible only if missing truly means none; a mode can suit categories but hides uncertainty.','median() → middle observed value|fillna(value) → replace gaps only|mode().iloc[0] → first most-common value; ties need a decision','Fill missing tip with the observed median tip, keeping all rows. This is an exercise assumption, not proof of the true tip.','df["tip"] = df["tip"].fillna(df["tip"].median())\ndf',{datasets:['messy','messy_games','messy_pets'],target:'df'});
add('W18','Remove duplicates',2,'Remove verified extra copies.','drop_duplicates keeps the first occurrence by default. In these fixtures identical full rows are confirmed accidental copies. In real data, two identical measurements can be legitimate. A business key subset must be chosen from the data definition.','df.drop_duplicates() → remove extra identical rows|keep="first" → retain first occurrence|subset=["order"] → compare only this key if it must be unique','Remove extra exact duplicate rows and preserve the first occurrence and its index.','df = df.drop_duplicates()\ndf',{datasets:['messy','messy_games','messy_pets'],target:'df'});
add('W19','Group and aggregate',3,'Create readable, named group summaries.','Named aggregation gives output columns clear names. Each name receives a tuple (input column, aggregation). as_index=False keeps group labels as a regular column. count counts known values; size counts all rows.','groupby("size", as_index=False) → one output row per size|mean_amount=("price", "mean") → output name, source, operation','Group by {c}. Return a DataFrame with {c}, mean_amount (mean {a}) and records (row count), in that order.','df.groupby("{c}", as_index=False).agg(mean_amount=("{a}", "mean"), records=("{a}", "size"))');
add('W20','Groupwise transformation',3,'Add a group statistic beside each original row.','agg reduces each group to one row. transform returns a value aligned to every original row, so you can add it as a column. It is useful for comparing an observation with its own group average.','groupby("size")["price"] → one measured column per group|transform("mean") → broadcast each mean back to its rows','Add group_mean containing the mean {a} for each row’s {c} category. Preserve all rows.','df["group_mean"] = df.groupby("{c}")["{a}"].transform("mean")\ndf',{target:'df'});
add('W21','Build a pivot table',3,'Summarise a measurement across two category axes.','pivot_table combines grouping and reshaping. index chooses row categories, columns chooses column categories, values chooses the measurement, and aggfunc chooses how repeats are summarised. Missing combinations remain NaN unless a justified fill_value is supplied.','index= → output row labels|columns= → output column labels|values= → numbers to summarise|aggfunc="mean" → average repeated combinations','Return a pivot table of mean {a}, with {c} on rows and {d} on columns. Leave absent combinations missing.','df.pivot_table(index="{c}", columns="{d}", values="{a}", aggfunc="mean")');
add('W22','Wide → long',3,'Turn measurement columns into variable/value rows.','melt keeps identifier columns and stacks the chosen measurement columns. The variable column tells you where each number came from. Row count increases because one original row contributes a row for each selected measurement.','id_vars=[...] → identifiers repeated beside each measure|value_vars=[...] → columns to stack|var_name / value_name → names for the new columns','Melt {a} and {b} into measure and value columns, retaining {id} as the identifier.','df.melt(id_vars=["{id}"], value_vars=["{a}", "{b}"], var_name="measure", value_name="value")');
add('W23','Long → wide',3,'Reshape unique identifier/measurement pairs.','pivot rearranges without aggregating. Each index/column pair must be unique; duplicates raise an error. Inspect duplicate keys, then choose an explicit aggregation with pivot_table if repeats are legitimate. Here long is prepared from the visible table.','pivot(index="name", columns="measure", values="value") → one column per measure|unique key → one value for each row/column pair','The supplied long table contains {id}, measure and value. Pivot it back with {id} on rows, measure on columns and value in cells.','long.pivot(index="{id}", columns="measure", values="value")',{datasets:['candy','pets','games'],setup:'long = df.melt(id_vars=["{id}"], value_vars=["{a}", "{b}"], var_name="measure", value_name="value")',stretch:'Duplicate one row in long with pd.concat([long, long.head(1)]). Why does pivot reject it?'});
add('W24','Combine tables by keys',3,'Join a lookup table while checking the relationship.','merge matches key values, not row positions. A left join retains every left row; unmatched labels receive missing values. validate="many_to_one" checks that lookup keys are unique and prevents accidental row multiplication.','on="size" → key shared by both tables|how="left" → preserve left rows|validate="many_to_one" → each lookup key occurs once','Join the supplied lookup table onto df using {c}. Keep every df row and validate a many-to-one join.','df.merge(lookup, on="{c}", how="left", validate="many_to_one")',{setup:'lookup = pd.DataFrame({"{c}": list(df["{c}"].unique()), "priority": list(range(1, df["{c}"].nunique() + 1))})'});
add('W25','Stack datasets',4,'Append compatible observations vertically.','concat stacks tables along rows by default. A list tells it which tables to combine. ignore_index=True makes a new consecutive index. Unlike merge, concat does not match key values; inspect column names and units first.','pd.concat([first, second]) → stack tables in list order|ignore_index=True → number new rows from zero','Stack the supplied first and second tables, in that order, with a fresh index.','pd.concat([first, second], ignore_index=True)',{setup:'first = df.iloc[:3].copy()\nsecond = df.iloc[3:].copy()'});
add('W26','Create bins',4,'Turn numbers into labelled intervals.','cut uses value boundaries; qcut uses sample quantiles to aim for similarly sized groups. Neither creates new information. Here right=True means each interval includes its right boundary, and include_lowest=True includes the minimum boundary. Tied values may prevent unique qcut edges.','pd.cut(values, bins=...) → intervals with chosen edges|labels=[...] → names in interval order|pd.qcut(values, q=2) → split at a sample quantile','Add half using cut with boundaries 0, {threshold}, and 100; labels "lower" and "upper". Include zero in the first bin.','df["half"] = pd.cut(df["{a}"], bins=[0, {threshold}, 100], labels=["lower", "upper"], include_lowest=True)\ndf',{target:'df',strictDtype:true,stretch:'Compare with pd.qcut(df["{a}"], q=2). Equal-width and equal-frequency bins answer different questions.'});
add('W27','Encode categories',4,'Represent category membership as indicator columns.','get_dummies produces a column for each observed label. Each row receives 1 for its label and 0 for the others. For prediction, learn the categories from training data and align future columns; this tiny exercise only demonstrates representation.','pd.get_dummies(df, columns=[...]) → encode selected columns|dtype=int → use 0 and 1 rather than False and True','One-hot encode {c} in df with integer indicator columns, preserving the other columns. Return the encoded DataFrame.','pd.get_dummies(df, columns=["{c}"], dtype=int)');
add('W28','Scale numeric columns',4,'Compare standardisation with min–max scaling.','StandardScaler subtracts the mean and divides by the population standard deviation. MinMaxScaler maps the observed minimum and maximum to 0 and 1. Scaling changes units, not information. For ML, fit on training data only and transform held-out data with the fitted scaler.','from sklearn.preprocessing import StandardScaler → load the scaling tool|fit_transform(table) → learn parameters then scale this table|df[["price"]] → a two-dimensional input, even for one column',['Standardise {a} and {b} using StandardScaler. Return the resulting two-column numeric array.','Scale {a} and {b} to the range 0–1 using MinMaxScaler. Return the two-column numeric array.','Standardise {a} and {b}. Return the array and consider why a future test set must use the fitted training scaler.'],['from sklearn.preprocessing import StandardScaler\nscaler = StandardScaler()\nscaler.fit_transform(df[["{a}", "{b}"]])','from sklearn.preprocessing import MinMaxScaler\nscaler = MinMaxScaler()\nscaler.fit_transform(df[["{a}", "{b}"]])','from sklearn.preprocessing import StandardScaler\nscaler = StandardScaler()\nscaler.fit_transform(df[["{a}", "{b}"]])']);
add('W29','Handle outliers responsibly',4,'Flag unusual values without deleting evidence.','An outlier rule is a prompt to investigate measurement, context and consequences. It is not proof of error. Keep original measurements and add a flag. clip(lower=..., upper=...) caps values only when a documented measurement or analysis rule justifies it.','quantile(0.75) → upper quartile|df["flag"] = test → retain a Boolean flag beside the observation|clip(...) → cap, only with a defensible reason','Add needs_review for values of {a} strictly above its 75th percentile. Keep every observation and original value.','df["needs_review"] = df["{a}"] > df["{a}"].quantile(0.75)\ndf',{target:'df',stretch:'If a sensor is known to saturate at 100, a separate capped column may be defensible. Why should the raw column still be retained?'});
add('W30','Vectorise before apply',5,'Choose a simple column operation before a row function.','Prefer arithmetic and .str operations first, dictionary map for lookups next, and apply only for logic without a direct column operation. apply is not automatically faster. lambda x: ... defines a small unnamed function; x is its input.','df["price"] * 1.1 → direct vectorised arithmetic|map(dictionary) → a value lookup|apply(lambda x: ...) → call a function on each value','Add adjusted equal to {a} multiplied by 1.1, rounded to two decimals. Use a direct column operation.','df["adjusted"] = (df["{a}"] * 1.1).round(2)\ndf',{target:'df',stretch:'Compare with df["{a}"].apply(lambda x: round(x * 1.1, 2)). Which expresses the intent more directly?'});
function chart(id,title,chapter,goal,explanation,syntax,task,body,options={}){
 const finish='\nax.set(title="{name}", xlabel="{a}", ylabel="{b}")\nfig.tight_layout()\nplt.show()';
 const solution=options.full||('import matplotlib.pyplot as plt\nimport seaborn as sns\n\nfig, ax = plt.subplots(figsize=(6, 4))\n'+body+finish);
 const taskEnd=options.taskEnd===undefined?' Give the chart title "{name}" and axis labels "{a}" and "{b}". Finish with fig.tight_layout() and plt.show().':options.taskEnd;
 return add(id,title,chapter,goal,explanation,syntax,task+taskEnd,solution,{datasets:['students','weather','games'],target:'plot',plot:{labels:true,...options.plot},...options});
}
chart('V01','Meet Figure and Axes',0,'Create the canvas and the plotting area.','Figure is the whole canvas. Axes is one plotting area on it. subplots returns both, so fig, ax = ... stores two results. Even one plotting area is called Axes. You will put Seaborn charts on that ax in later cards.','import matplotlib.pyplot as plt → load plotting tools|fig, ax = → unpack two returned objects|plt.subplots(figsize=(6, 4)) → canvas width and height in inches|plt.show() → display the figure','Create one empty Figure with one Axes at 6 by 4 inches.','',{plot:{empty:true,size:true}});
chart('V02','Finish a chart properly',0,'Make a chart readable before sharing it.','The supplied scatter call makes marks. Your job is the finish: a meaningful title and axis labels, sufficient figure size, then tight_layout to reduce clipping. Once ax exists, use its methods rather than global plt.title or plt.xlabel.','ax.set(title=..., xlabel=..., ylabel=...) → name the chart and axes|ax.set_title(...) → change just the title|fig.tight_layout() → adjust spacing|plt.show() → display','Complete the supplied chart at 6 by 4 inches.','sns.scatterplot(data=df, x="{a}", y="{b}", ax=ax)',{plot:{size:true}});
chart('V03','Map variables visually',0,'Connect columns to visual channels.','x and y locate points. hue maps a category to colour; style maps it to marker shape; size maps a numeric variable to marker area. A mapping names a column; color="blue" sets one fixed appearance. Do not add channels without a question.','data=df → the table supplying all mappings|x="hours", y="score" → horizontal and vertical variables|hue="club" → colour by category|style="club" → redundant shapes for accessibility|size="hours" → map magnitude to marker area','Use sns.scatterplot: x={a}, y={b}, hue={c}, style={c}, size={a}.','sns.scatterplot(data=df, x="{a}", y="{b}", hue="{c}", style="{c}", size="{a}", ax=ax)',{plot:{legend:true,sizes:true,colors:true}});
const distribution=[
 ['V04','Histogram','See how values fall into bins.','A histogram counts observations within numeric intervals. Different bins can change the impression. Six or eight observations are enough to learn syntax, but too few to infer a stable population distribution.','sns.histplot → count values inside bins|bins=4 → four intervals','Use sns.histplot for {a} with 4 bins.','sns.histplot(data=df, x="{a}", bins=4, ax=ax)'],
 ['V05','Density curve','Understand a smoothed view of a distribution.','A KDE spreads each observation into a smooth bump and combines the bumps. It shows density, not counts. bw_adjust controls smoothing; cut=0 stops the curve at the observed range. Tiny-sample curves are demonstrations, not strong evidence.','sns.kdeplot → a smoothed density estimate|bw_adjust=1 → default bandwidth multiplier|cut=0 → stay within observed endpoints','Use sns.kdeplot for {a}, with bw_adjust=1 and cut=0.','sns.kdeplot(data=df, x="{a}", bw_adjust=1, cut=0, ax=ax)'],
 ['V06','ECDF','Read the fraction at or below a value.','An empirical cumulative distribution rises at observed values. At any x, its height is the fraction of observations at or below x. Unlike a histogram it needs no bin choice; unlike a KDE it does not smooth away the observations.','sns.ecdfplot → cumulative fraction from observations|x= → numeric column along the horizontal axis','Use sns.ecdfplot for {a}.','sns.ecdfplot(data=df, x="{a}", ax=ax)'],
 ['V07','Rug marks','Keep individual observations visible beneath a distribution.','Rug marks place one small tick per observation along an axis. Combine them with a histogram or density curve on the same Axes. Overlapping marks can hide repeats, so do not treat a visible mark count as a reliable row count.','sns.rugplot → a tick at each observed x|ax=ax → draw into the same plotting area','Use a 4-bin sns.histplot of {a}, then overlay sns.rugplot for {a} on the same ax.','sns.histplot(data=df, x="{a}", bins=4, ax=ax)\nsns.rugplot(data=df, x="{a}", ax=ax)']
];
for(const [id,title,goal,explanation,syntax,task,body] of distribution)chart(id,title,Number(id.slice(1))<=6?0:1,goal,explanation,syntax,task,body,{taskEnd:' Title the chart "{name}"; label x "{a}" and y "'+({V04:'Count',V05:'Density',V06:'Proportion',V07:'Count'}[id])+'". Finish with tight_layout and show.',full:'import matplotlib.pyplot as plt\nimport seaborn as sns\n\nfig, ax = plt.subplots(figsize=(6, 4))\n'+body+'\nax.set(title="{name}", xlabel="{a}", ylabel="'+({V04:'Count',V05:'Density',V06:'Proportion',V07:'Count'}[id])+'")\nfig.tight_layout()\nplt.show()'});
function categorical(id,title,goal,explanation,syntax,method,args='',options={}){
 const count=method==='countplot',y=count?'Count':'{a}';
 const body=`sns.${method}(data=df, x="{c}"${count?'':', y="{a}"'}${args}, ax=ax)`;
 return chart(id,title,Number(id.slice(1))<=12?1:2,goal,explanation,syntax,`Use sns.${method} with {c} on x${count?' to count its observations':' and {a} on y'}${options.extraTask||''}.`,body,{datasets:['candy','cafe','pets'],taskEnd:` Use title "{name}", x label "{c}" and y label "${y}". Finish with tight_layout and show.`,full:'import matplotlib.pyplot as plt\nimport seaborn as sns\n\nfig, ax = plt.subplots(figsize=(6, 4))\n'+body+`\nax.set(title="{name}", xlabel="{c}", ylabel="${y}")\nfig.tight_layout()\nplt.show()`,plot:{categorical:true,...options.plot},...options});
}
categorical('V08','Count categories','Count observations, not a numeric measurement.','countplot counts rows in each category. It does not take a numeric y value. This is the visual counterpart of value_counts. Compare category order and include a baseline at zero.','sns.countplot → count rows per category|x="flavour" → categories along the x axis','countplot');
categorical('V09','Compare averages','Distinguish an estimate from a count.','barplot estimates a numeric quantity within each category; its default is the mean. A tall bar is not a large group. Here errorbar=None omits uncertainty to isolate bar height; that omission must never be mistaken for certainty.','sns.barplot → an estimated summary per group|estimator="mean" → group average|errorbar=None → deliberately hide uncertainty','barplot',', estimator="mean", errorbar=None',{extraTask:', using estimator="mean" and errorbar=None'});
categorical('V10','Point estimates','Show a group estimate with uncertainty.','pointplot marks an estimate without filled bars. Here errorbar="sd" shows one standard deviation around the mean: spread of observations, not a confidence interval for the mean. A bootstrap CI is another choice, but tiny groups do not support strong claims.','sns.pointplot → a point for each estimate|errorbar="sd" → spread of observed values|capsize=0.15 → caps at interval ends','pointplot',', errorbar="sd", capsize=0.15',{extraTask:', using errorbar="sd" and capsize=0.15'});
categorical('V11','Box plot','Read a median and interquartile spread.','A box spans the 25th to 75th percentiles, with a median line. Default whiskers reach observed values within 1.5 IQR of the box. Points beyond them are flags, not proven errors. Very small groups make quartiles unstable.','sns.boxplot → compact group distributions|IQR → upper quartile minus lower quartile','boxplot');
categorical('V12','Violin plot','Recognise smoothing inside categorical distributions.','A violin mirrors a density curve within each category. Its silhouette depends on smoothing and sample size. Use cut=0 to keep it within observed endpoints. With this tiny table, learn the API and prefer raw points for honest interpretation.','sns.violinplot → mirrored density by category|cut=0 → do not extend beyond observed values','violinplot',', cut=0',{extraTask:', using cut=0'});
categorical('V13','Raw points','Show the observations behind a group summary.','stripplot draws every observation. jitter shifts points slightly sideways to reduce overlap; it does not change the measured y value. A raw-point view is especially useful with a tiny sample.','sns.stripplot → one marker per observation|jitter=0.15 → small horizontal displacement','stripplot',', jitter=0.15',{extraTask:', using jitter=0.15',plot:{jitter:true,categorical:true}});
categorical('V14','Non-overlapping raw points','Separate observations without changing their values.','swarmplot moves points along the category direction to avoid overlap. It can become slow or fail to place every point in crowded groups. With larger data, consider transparency, smaller points or another summary.','sns.swarmplot → spread markers to avoid overlap|size=5 → marker size, not a data mapping','swarmplot',', size=5',{extraTask:', using size=5',plot:{jitter:true,categorical:true}});
categorical('V15','Large-sample categorical distribution','Recognise a letter-value plot and its limits.','boxenplot shows nested quantile bands and is useful for larger groups. Our six-row teaching table demonstrates its syntax only; there is too little data to estimate detailed tails. Use raw points when the sample is this small.','sns.boxenplot → nested quantile bands|tails → the less common low and high values','boxenplot');
chart('V16','Scatter plot',2,'Plot two numeric measurements observation by observation.','Each point pairs the x and y values from one row. Scatter plots reveal form, clusters and unusual observations. They show associations, not causal effects. A tiny cloud is not enough to establish a dependable relationship.','sns.scatterplot(data=df, x=..., y=..., ax=ax) → one point per row','Use sns.scatterplot for {a} against {b}.','sns.scatterplot(data=df, x="{a}", y="{b}", ax=ax)');
chart('V17','Add dimensions to scatter',2,'Use colour and shape without losing readability.','Map a category to both hue and style so colour is not the only cue. size can encode magnitude, but too many mappings increase reading effort. Check the legend and ask whether the extra dimension answers your question.','hue= → category colours|style= → category marker shapes|size= → numeric marker areas','Use sns.scatterplot with x={a}, y={b}, hue={c}, style={c} and size={a}.','sns.scatterplot(data=df, x="{a}", y="{b}", hue="{c}", style="{c}", size="{a}", ax=ax)',{plot:{legend:true,sizes:true,colors:true}});
chart('V18','Line plot',2,'Show a relationship along an ordered numeric axis.','A line implies an ordered progression, so do not connect arbitrary categories. Seaborn sorts x by default and averages repeated x values. Here estimator=None preserves each observation; a later card compares that choice with aggregation.','sns.lineplot → connect observations along x|estimator=None → do not average repeated x|marker="o" → show the observed points','Use sns.lineplot with x={a}, y={b}, estimator=None and marker="o".','sns.lineplot(data=df, x="{a}", y="{b}", estimator=None, marker="o", ax=ax)');
chart('V19','Understand lineplot aggregation',3,'Notice when a line summarises repeated x values.','When x repeats, the default lineplot computes the mean y at each x. errorbar="sd" displays spread at repeated x values; single observations cannot estimate that spread. estimator=None instead connects raw observations. Neither choice turns unrelated categories into a time series.','estimator="mean" → one mean for each x|errorbar="sd" → spread, not a confidence interval|estimator=None → retain raw values','Use sns.lineplot with mean {b} at each {a}, errorbar="sd" and marker="o".','sns.lineplot(data=df, x="{a}", y="{b}", estimator="mean", errorbar="sd", marker="o", ax=ax)',{datasets:['students','students','students'],setup:'df["hours"] = [1, 1, 2, 2, 3, 3, 4, 4]',stretch:'Use estimator=None and errorbar=None. Why do repeated x values now have several y values?'});
chart('V20','Regression view',3,'View a fitted linear trend alongside observations.','regplot overlays a fitted line on a scatter plot. The line summarises a model assumption; it is not a claim of causation. Here ci=None omits its uncertainty band to focus on the trend. Always inspect the points and ask if a line is suitable.','sns.regplot → points and fitted line|ci=None → omit the confidence band','Use sns.regplot with x={a}, y={b} and ci=None.','sns.regplot(data=df, x="{a}", y="{b}", ci=None, ax=ax)');
chart('V21','Residual view',3,'Inspect what a fitted line leaves unexplained.','A residual is observed y minus predicted y. residplot fits a line and plots its residuals. Curves or a changing vertical spread may expose a poor linear description. A few residuals are not a complete model diagnostic.','sns.residplot → x against residuals after a linear fit|zero line → predictions equal observations','Use sns.residplot with x={a} and y={b}. Label y "Residual".','sns.residplot(data=df, x="{a}", y="{b}", ax=ax)',{taskEnd:' Title "{name}"; x label "{a}"; y label "Residual". Finish with tight_layout and show.',full:'import matplotlib.pyplot as plt\nimport seaborn as sns\n\nfig, ax = plt.subplots(figsize=(6, 4))\nsns.residplot(data=df, x="{a}", y="{b}", ax=ax)\nax.set(title="{name}", xlabel="{a}", ylabel="Residual")\nfig.tight_layout()\nplt.show()'});
chart('V22','Correlation heatmap',3,'Show a correlation matrix on a fixed colour scale.','First compute numeric correlations, then pass that matrix to heatmap. Fix vmin=-1 and vmax=1 so colours mean the same across charts. A diverging palette centred at zero separates positive from negative relationships. Correlation still does not imply causation.','df.corr(numeric_only=True) → prepare the matrix|annot=True → print cell values|vmin=-1, vmax=1, center=0 → meaningful colour limits','Plot sns.heatmap of numeric correlations with annot=True, vmin=-1, vmax=1, center=0 and cmap="vlag".','matrix = df.corr(numeric_only=True)\nsns.heatmap(matrix, annot=True, vmin=-1, vmax=1, center=0, cmap="vlag", ax=ax)',{plot:{clim:true}});
chart('V23','Categorical / matrix heatmap',3,'Prepare a matrix before colouring its cells.','A heatmap needs a two-dimensional matrix. crosstab provides category counts; pivot_table provides aggregated measurements. Write the question first: a count of observations is different from their average value.','pd.crosstab(...) → category count matrix|sns.heatmap(matrix, annot=True, fmt="d") → print integer counts','Build a crosstab of {c} by {d}, then sns.heatmap with annot=True, fmt="d", cmap="Blues".','matrix = pd.crosstab(df["{c}"], df["{d}"])\nsns.heatmap(matrix, annot=True, fmt="d", cmap="Blues", ax=ax)');
chart('V24','Multiple subplots',3,'Manage two charts on one Figure.','subplots(1, 2) returns one Figure and an array of two Axes. axes[0] is left and axes[1] is right. Pass the intended Axes to every Seaborn call. Finish the whole Figure once.','fig, axes = plt.subplots(1, 2, figsize=(10, 4)) → two plotting areas|axes[0] → first Axes|ax=axes[1] → draw on the second Axes','Create a two-panel Figure: a 4-bin histogram of {a} on the left and a scatter of {a} against {b} on the right.', '',{taskEnd:' Use panel titles "Distribution" and "Relationship", x labels "{a}", and y labels "Count" and "{b}". Finish the Figure with tight_layout and show.',full:'import matplotlib.pyplot as plt\nimport seaborn as sns\n\nfig, axes = plt.subplots(1, 2, figsize=(10, 4))\nsns.histplot(data=df, x="{a}", bins=4, ax=axes[0])\nsns.scatterplot(data=df, x="{a}", y="{b}", ax=axes[1])\naxes[0].set(title="Distribution", xlabel="{a}", ylabel="Count")\naxes[1].set(title="Relationship", xlabel="{a}", ylabel="{b}")\nfig.tight_layout()\nplt.show()'});
chart('V25','Legends and palettes',4,'Make category mappings readable without colour alone.','Use a colourblind-friendly palette and redundant shapes. ax.legend controls the legend on that Axes. A legend explains mapped variables, while directly labelled marks can sometimes be simpler. Avoid red/green as the only distinction.','palette="colorblind" → a palette designed for categorical separation|ax.legend(title=...) → label the category key|style= → another cue alongside hue','Plot {a} against {b} with sns.scatterplot, hue={c}, style={c} and palette="colorblind". Set the legend title to "Category".','sns.scatterplot(data=df, x="{a}", y="{b}", hue="{c}", style="{c}", palette="colorblind", ax=ax)\nax.legend(title="Category")',{plot:{legend:true,colors:true}});
chart('V26','Axes and scales',4,'Choose limits, ticks and transformations consciously.','Axes methods control what the viewer sees. A log scale represents multiplicative ratios and requires positive values; label it clearly. Limits can hide data. Tick rotation can prevent overlap but should not make labels hard to read.','ax.set_xscale("log") → logarithmic x axis|ax.set_ylim(bottom=0) → y begins at zero|ax.tick_params(axis="x", labelrotation=30) → rotate x labels','Scatter {a} against {b}, set x to log scale, set the y lower limit to zero, and rotate x tick labels by 30 degrees.','sns.scatterplot(data=df, x="{a}", y="{b}", ax=ax)\nax.set_xscale("log")\nax.set_ylim(bottom=0)\nax.tick_params(axis="x", labelrotation=30)',{plot:{limits:true,ticks:true}});
chart('V27','Reference lines',4,'Add a benchmark with a clear meaning.','axhline draws a horizontal benchmark in y data units; axvline draws a vertical one in x data units. A line needs an explanation, such as an observed median or a documented target. It is not automatically a decision boundary.','ax.axhline(y, ...) → horizontal reference|ax.axvline(x, ...) → vertical reference|linestyle="--" → dashed line','Scatter {a} against {b}; add dashed reference lines at median {a} and median {b}.','sns.scatterplot(data=df, x="{a}", y="{b}", ax=ax)\nax.axvline(df["{a}"].median(), linestyle="--")\nax.axhline(df["{b}"].median(), linestyle="--")');
chart('V28','Annotate important points',4,'Explain an observation directly on the chart.','annotate puts text beside a point. xy gives the point in data coordinates. xytext gives the text position; with textcoords="offset points" it is an offset from the observation. An arrow can make the connection clear.','ax.annotate("Peak", xy=(x, y), ...) → label a point|idxmax() → row label of the largest value|arrowprops={"arrowstyle": "->"} → point an arrow at it','Scatter {a} against {b}. Label the row with highest {b} "Peak", offset by (8, 8) points, with an arrow.','sns.scatterplot(data=df, x="{a}", y="{b}", ax=ax)\npeak = df.loc[df["{b}"].idxmax()]\nax.annotate("Peak", xy=(peak["{a}"], peak["{b}"]), xytext=(8, 8), textcoords="offset points", arrowprops={"arrowstyle": "->"})',{plot:{annotations:true}});
chart('V29','Exact precomputed bars',4,'Draw numbers that have already been calculated.','Use ax.bar when bar heights are exact supplied totals or a precomputed summary. Unlike Seaborn barplot, ax.bar does not estimate or aggregate repeated categories. Here we explicitly calculate totals first.','groupby(...).sum() → calculate exact group totals|ax.bar(totals.index, totals.values) → draw those heights','Sum {a} by {c}, then use ax.bar to draw those exact totals.','totals = df.groupby("{c}")["{a}"].sum()\nax.bar(totals.index, totals.values)',{datasets:['candy','cafe','pets']});
chart('V30','Stacked bars',4,'Build a part-to-whole bar from known components.','The bottom argument places the second component on top of the first. Use compatible units and make the parts clear. Only the first layer shares a zero baseline, so comparing upper segments is harder. Here each total is split into 60% and 40%.','ax.bar(..., bottom=first) → stack above first|label= → name each component|ax.legend() → show component names','Sum {a} by {c}. Draw 60% as "First" and stack the remaining 40% as "Second"; show a legend.','totals = df.groupby("{c}")["{a}"].sum()\nfirst = totals * 0.6\nsecond = totals * 0.4\nax.bar(totals.index, first, label="First")\nax.bar(totals.index, second, bottom=first, label="Second")\nax.legend()',{datasets:['candy','cafe','pets'],plot:{legend:true}});
function figureLesson(id,title,goal,explanation,syntax,task,call,options={}){
return add(id,title,5,goal,explanation,syntax,task+' This is a figure-level exception: do not create fig, ax first. Finish with g.figure.tight_layout() and plt.show().','import matplotlib.pyplot as plt\nimport seaborn as sns\n\n'+call+'\ng.figure.tight_layout()\nplt.show()',{datasets:['students','weather','games'],target:'plot',plot:{labels:true},...options});
}
figureLesson('V31','Pair relationships','Explore several pairwise relationships in one figure.','pairplot owns its Figure and makes a grid of pairwise scatter plots, with distributions on the diagonal. Do not pass ax=. Limit vars to the numeric columns you need; a large grid quickly becomes unreadable.','g = sns.pairplot(...) → create a whole grid and keep its handle|vars=[...] → choose numeric columns|diag_kind="hist" → histogram on the diagonal|g.figure → the grid’s Figure','Use pairplot for {a} and {b}, hue={c}, diag_kind="hist".','g = sns.pairplot(data=df, vars=["{a}", "{b}"], hue="{c}", diag_kind="hist")');
figureLesson('V32','Joint relationships','Connect a relationship to its marginal distributions.','jointplot creates a central relationship plot and marginal distribution axes. It is a figure-level function with its own Figure. g.ax_joint gives access to the central Axes when you want to refine it.','g = sns.jointplot(...) → create a relationship and its margins|kind="scatter" → central scatter plot|g.ax_joint → central Axes','Use jointplot with x={a}, y={b}, kind="scatter".','g = sns.jointplot(data=df, x="{a}", y="{b}", kind="scatter")');
const facet=figureLesson('V33','Faceting','Repeat the same chart across comparable subsets.','relplot, catplot and displot create their own Figures. col names the variable used to split panels; kind chooses the underlying chart. Keep scales comparable when comparisons matter. height and aspect describe each panel, unlike figsize for a whole Figure.','relplot(kind="scatter") → relationship panels|catplot(kind="box") → categorical panels|displot(kind="hist") → distribution panels|col= → one panel per category','Create relplot scatter panels of {a} against {b}, split by {c}, using height=3.','g = sns.relplot(data=df, x="{a}", y="{b}", col="{c}", kind="scatter", height=3)');
facet.rounds[1].task='Use catplot with x="sky", y="temperature", col="station", kind="box", height=3. It creates its own Figure; finish with g.figure.tight_layout() and plt.show().';
facet.rounds[1].solution='import matplotlib.pyplot as plt\nimport seaborn as sns\n\ng = sns.catplot(data=df, x="sky", y="temperature", col="station", kind="box", height=3)\ng.figure.tight_layout()\nplt.show()';
facet.rounds[2].task='Use displot of minutes, split by genre, with kind="hist", bins=4, height=3. Finish the returned Figure and display it.';
facet.rounds[2].solution='import matplotlib.pyplot as plt\nimport seaborn as sns\n\ng = sns.displot(data=df, x="minutes", col="genre", kind="hist", bins=4, height=3)\ng.figure.tight_layout()\nplt.show()';
chart('V34','Save a figure',5,'Export the specific Figure you have finished.','fig.savefig writes the Figure to a file. Save after arranging labels, usually before show. dpi sets raster resolution; bbox_inches="tight" includes surrounding labels. In this local browser workspace the file appears as a download beneath the output.','fig.savefig("chart.png", dpi=150, bbox_inches="tight") → export this Figure|.png → raster image format|dpi=150 → pixels per inch','Scatter {a} against {b}, finish its title and labels, then save chart.png at 150 dpi with a tight bounding box before displaying.', '',{taskEnd:' Use title "{name}", x label "{a}", y label "{b}".',full:'import matplotlib.pyplot as plt\nimport seaborn as sns\n\nfig, ax = plt.subplots(figsize=(6, 4))\nsns.scatterplot(data=df, x="{a}", y="{b}", ax=ax)\nax.set(title="{name}", xlabel="{a}", ylabel="{b}")\nfig.tight_layout()\nfig.savefig("chart.png", dpi=150, bbox_inches="tight")\nplt.show()',plot:{export:true}});
chart('V35','Choose the right chart',5,'Translate a question into a suitable visual form.','A numeric distribution suggests a histogram or ECDF. Two numeric variables suggest scatter. Category counts suggest countplot; a numeric distribution by category suggests raw points or boxes. Choose the question first, then the variables, then the chart.','question → what are we trying to learn?|variable types → numeric, categorical or ordered?|chart → a visual encoding that answers the question','How does {b} vary with {a}? Build a scatter plot to inspect this numeric relationship.','sns.scatterplot(data=df, x="{a}", y="{b}", ax=ax)');
chart('V36','Avoid misleading charts',5,'Make the scale and selection honest.','Bars encode magnitude through length, so start them at zero. Arbitrary category order can conceal comparisons; sort deliberately and explain it. Use raw points or transparency for overplotting. Avoid decorative 3D, which distorts comparisons. Include units and do not hide inconvenient rows.','sort_values(ascending=False) → a meaningful category order|ax.set_ylim(bottom=0) → honest bar-length baseline|alpha= → transparency for overlapping points','Sum {a} by {c}, sort totals from highest to lowest, draw exact bars, and start y at zero.','totals = df.groupby("{c}")["{a}"].sum().sort_values(ascending=False)\nax.bar(totals.index, totals.values)\nax.set_ylim(bottom=0)',{datasets:['candy','cafe','pets'],plot:{limits:true}});
function review(id,deck,chapter,title,after,sourceIds){
 const rounds=sourceIds.map((sourceId,i)=>{
  const original=lessons.find(x=>x.id===sourceId).rounds[2];
  return {...original,id:`${id}-${i+1}`,label:`Task ${i+1}`,starter:'# Bring together what you remember\n',retrieves:sourceId};
 });
 lessons.push({id,deck,chapter,title,after,goal:'Retrieve earlier skills on a fresh table.',explanation:'A pause for retrieval. Work from the given data and instructions first. Use Hint if you need a cue, then compare your result with the table. These tasks reuse skills you have already met.',syntax:[],minutes:12,review:true,rounds});
}
review('IR1','inspect',0,'Review · First contact','I05',['I02','I03','I04','I05']);
review('IR2','inspect',1,'Review · Select with intent','I11',['I07','I09','I11']);
review('IR3','inspect',2,'Review · Find the surprises','I17',['I12','I15','I16','I17']);
review('WR1','wrangle',0,'Review · Keep the evidence','W06',['W01','W03','W06']);
review('WR2','wrangle',2,'Review · Values with meaning','W12',['W07','W10','W12']);
review('WR3','wrangle',2,'Review · Gaps and duplicates','W18',['W14','W16','W17','W18']);
review('WR4','wrangle',3,'Review · Reshape and connect','W24',['W19','W20','W22','W24']);
review('WR5','wrangle',5,'Review · Prepare responsibly','W30',['W25','W26','W28','W29']);
review('VR1','visualise',0,'Review · A readable distribution','V06',['V02','V04','V06']);
review('VR2','visualise',1,'Review · Counts, averages, spread','V12',['V08','V09','V11']);
review('VR3','visualise',2,'Review · Points and relationships','V18',['V13','V17','V18']);
review('VR4','visualise',3,'Review · Inspect the model view','V24',['V20','V21','V22','V24']);
review('VR5','visualise',4,'Review · Finish with a purpose','V30',['V25','V27','V28','V30']);
review('VR6','visualise',5,'Review · Figure-level exceptions','V36',['V31','V32','V33','V36']);
const inspectFinal=add('I22','Inspect checkpoint',3,'Profile an unfamiliar eight-row table from scratch.','Use your inspection toolkit before changing any observations. Read the table, check types and missingness, then compare categories. This checkpoint introduces no new syntax.','df.shape → rows and columns|df.dtypes → types|isna().sum() → missing counts|value_counts() → category counts','Profile the table without changing df. Save a dictionary named profile with keys "shape", "columns", "types", "missing" and "categories": use shape, a list of columns, dtypes, missing counts per column and value_counts for {c}. Display profile.','profile = {\n    "shape": df.shape,\n    "columns": list(df.columns),\n    "types": df.dtypes,\n    "missing": df.isna().sum(),\n    "categories": df["{c}"].value_counts()\n}\nprofile',{datasets:['messy','students','weather'],minutes:15});
inspectFinal.review=true;inspectFinal.rounds.forEach(r=>r.starter='# Inspect first; preserve the original table\n');
const wrangleFinal=add('W31','Wrangle checkpoint',5,'Clean a messy order table end to end.','These order records contain confirmed extra copies, inconsistent text, invalid numeric text and invalid dates. Work on a separate table; preserve missing prices rather than inventing a sale amount. The observed median tip is an explicit temporary imputation assumption.','copy() → keep df untouched|drop_duplicates() → remove confirmed extra copies|to_numeric / to_datetime → parse explicitly|fillna(median) → documented assumption','Create clean as a separate copy. Remove extra identical rows. Strip and lowercase drink; strip and title-case size. Convert price to numeric and date to datetime, coercing invalid entries. Fill missing tip with the median after deduplication. Sort by order and reset the index. Keep all other values and retain rows with unknown price. Display clean.','clean = df.copy()\nclean = clean.drop_duplicates()\nclean["drink"] = clean["drink"].str.strip().str.lower()\nclean["size"] = clean["size"].str.strip().str.title()\nclean["price"] = pd.to_numeric(clean["price"], errors="coerce")\nclean["date"] = pd.to_datetime(clean["date"], format="%Y-%m-%d", errors="coerce")\nclean["tip"] = clean["tip"].fillna(clean["tip"].median())\nclean = clean.sort_values("order").reset_index(drop=True)\nclean',{datasets:['messy','messy_games','messy_pets'],target:'copy',strictDtype:true,minutes:20});
wrangleFinal.review=true;wrangleFinal.rounds.forEach(r=>r.starter='# Plan the cleaning steps, then create clean\n');
const visualFinal=chart('V37','Visualise checkpoint',5,'Build a coherent three-chart mini-report.','Reuse inspection, filtering, aggregation and chart finishing. Each chart should answer a different question about the same selected observations. Keep the sample-size limitation in mind when explaining a pattern.','filter → define the report population|histogram → one numeric distribution|scatter → a numeric relationship|exact bars → precomputed group totals','Keep rows with {a} greater than {threshold} in a table named selected. Build three separate Figures: a 4-bin histogram of selected {a}; a scatter of selected {a} against {b}; and exact bars of total selected {a} by {c}.','',{datasets:['students','weather','games'],minutes:20,taskEnd:' Use titles "Distribution", "Relationship", "Totals". Label axes ({a}, Count), ({a}, {b}) and ({c}, Total). Finish and show each Figure.',full:'import matplotlib.pyplot as plt\nimport seaborn as sns\n\nselected = df[df["{a}"] > {threshold}]\n\nfig, ax = plt.subplots(figsize=(6, 4))\nsns.histplot(data=selected, x="{a}", bins=4, ax=ax)\nax.set(title="Distribution", xlabel="{a}", ylabel="Count")\nfig.tight_layout()\nplt.show()\n\nfig, ax = plt.subplots(figsize=(6, 4))\nsns.scatterplot(data=selected, x="{a}", y="{b}", ax=ax)\nax.set(title="Relationship", xlabel="{a}", ylabel="{b}")\nfig.tight_layout()\nplt.show()\n\ntotals = selected.groupby("{c}")["{a}"].sum()\nfig, ax = plt.subplots(figsize=(6, 4))\nax.bar(totals.index, totals.values)\nax.set(title="Totals", xlabel="{c}", ylabel="Total")\nfig.tight_layout()\nplt.show()'});
visualFinal.review=true;visualFinal.rounds.forEach(r=>r.starter='# Three questions, three charts\n');
// Order reviews immediately after their retrieval boundary; preserve published card IDs.
const ordered=[];
for(const deck of decks){
 for(const lesson of lessons.filter(l=>l.deck===deck.id&&!l.after).sort((a,b)=>Number(a.id.slice(1))-Number(b.id.slice(1)))){
  ordered.push(lesson,...lessons.filter(l=>l.after===lesson.id));
 }
}
// Construction starts with four rows and two columns so every literal is readable.
const construction = ordered.find(l => l.id === 'I01');
['candy','cafe','pets'].forEach((key,i) => {
 const original = datasets[key];
 const smallKey = key + '_build';
 datasets[smallKey] = {...original, name:original.name + ' · first table', columns:{[original.id]:original.columns[original.id].slice(0,4), [original.a]:original.columns[original.a].slice(0,4)}};
 const r=construction.rounds[i];r.dataset=smallKey;
 r.task='Write a dictionary named data using the two columns and four rows in the given table. Import pandas as pd, create df from data, and display df.';
 r.solution=setupCode(smallKey)+'\ndf';
 r.starter=i===0?r.solution.replace('pd.DataFrame','pd.____'):i===1?'# Create data, then construct df\n':'# Build this table from scratch\n';
 r.hint='Each quoted column name is a dictionary key. Its list contains the four row values. Use pd.DataFrame(data) to construct the table.';
});
// Keep chart labels faithful to the quantity encoded on each axis.
for (const lesson of ordered) {
 for (const round of lesson.rounds) {
  const sourceId = round.retrieves || lesson.id;
  const d = datasets[round.dataset];
  const labels = sourceId === 'V22' ? ['Variable', 'Variable'] : sourceId === 'V23' ? [d.d, d.c] : ['V29','V30','V36'].includes(sourceId) ? [d.c, 'Total'] : null;
  if (labels) {
   const old = `xlabel="${d.a}", ylabel="${d.b}"`;
   const replacement = `xlabel="${labels[0]}", ylabel="${labels[1]}"`;
   round.solution = round.solution.replace(old, replacement);
   round.starter = round.starter.replace(old, replacement);
   round.task = round.task.replace(`axis labels "${d.a}" and "${d.b}"`, `axis labels "${labels[0]}" and "${labels[1]}"`);
  }
 }
 if (!lesson.review) lesson.example = lesson.rounds[0].solution;
}
// Repeated x values in three different contexts, with the exact given table visible.
const lineAggregation = ordered.find(l => l.id === 'V19');
['students','weather','games'].forEach((key, i) => {
 const d = datasets[key];
 const repeated = {...d, name: d.name + ' · repeated measurements', columns: Object.fromEntries(Object.entries(d.columns).map(([k,v]) => [k, [...v]]))};
 repeated.columns[d.a] = d.columns[d.a].map((v, row, values) => values[row - row % 2]);
 const datasetKey = key + '_repeated';
 datasets[datasetKey] = repeated;
 const r = lineAggregation.rounds[i];
 r.dataset = datasetKey; r.setup = '';
 r.solution = fill('import matplotlib.pyplot as plt\nimport seaborn as sns\n\nfig, ax = plt.subplots(figsize=(6, 4))\nsns.lineplot(data=df, x="{a}", y="{b}", estimator="mean", errorbar="sd", marker="o", ax=ax)\nax.set(title="{name}", xlabel="{a}", ylabel="{b}")\nfig.tight_layout()\nplt.show()', repeated, i);
 r.task = fill('Use sns.lineplot with mean {b} at each {a}, errorbar="sd" and marker="o". Give the chart title "{name}" and axis labels "{a}" and "{b}". Finish with tight_layout and show.', repeated, i);
 r.starter = i === 0 ? r.solution.replace('sns.lineplot', 'sns.____') : '# Your Python\n';
});
lineAggregation.example = lineAggregation.rounds[0].solution;
// Chart choice changes the question, not just the column names.
const chartChoice=ordered.find(l=>l.id==='V35');
chartChoice.rounds[1].task='How are the eight temperatures distributed? Draw a four-bin histogram. Title it "Weather diary" and label the axes "temperature" and "Count". Finish and display the Figure.';
chartChoice.rounds[1].solution='import matplotlib.pyplot as plt\nimport seaborn as sns\n\nfig, ax = plt.subplots(figsize=(6, 4))\nsns.histplot(data=df, x="temperature", bins=4, ax=ax)\nax.set(title="Weather diary", xlabel="temperature", ylabel="Count")\nfig.tight_layout()\nplt.show()';
chartChoice.rounds[2].dataset='movies';
chartChoice.rounds[2].task='Which genres occur most often in Movie night? Draw the category counts in their order of first appearance. Title it "Movie night" and label the axes "genre" and "Count". Finish and display the Figure.';
chartChoice.rounds[2].solution='import matplotlib.pyplot as plt\nimport seaborn as sns\n\nfig, ax = plt.subplots(figsize=(6, 4))\nsns.countplot(data=df, x="genre", ax=ax)\nax.set(title="Movie night", xlabel="genre", ylabel="Count")\nfig.tight_layout()\nplt.show()';
chartChoice.rounds[1].starter='# Choose a chart for a numeric distribution\n';
chartChoice.rounds[2].starter='# Choose a chart for category frequencies\n';
// Derive a useful guided blank from the actual step, never display a complete answer as a starter.
for(const lesson of ordered){
 for(const round of lesson.rounds){
  if(!lesson.review&&round.label==='Follow'&&!round.starter.includes('____')){
   const lines=round.solution.split('\n');
   const index=lines.findIndex(line=>line.includes('sns.')||line.startsWith('df = ')||line.startsWith('df[')||line.includes('scaler.fit_transform'));
   if(index>=0)lines[index]=lines[index].replace(/\.([a-zA-Z_]\w*)(?=\()/,'.____').replace(/^(df = df)\[/,'$1[____');
   else lines[lines.length-1]='# Write the result here';
   round.starter=lines.join('\n');
  }
  if(lesson.review){round.label=`Task ${lesson.rounds.indexOf(round)+1}`;}
 }
}
// The guided gap belongs to this lesson's skill, not the repeated final show().
for (const lesson of ordered.filter(l => !l.review)) {
 const r=lesson.rounds[0];
 if (r.target==='plot') {
  const specific={V01:'plt.subplots',V02:'ax.set',V07:'sns.rugplot',V24:'plt.subplots',V25:'ax.legend',V26:'ax.set_xscale',V27:'ax.axvline',V28:'ax.annotate',V29:'ax.bar',V30:'ax.bar',V34:'fig.savefig',V36:'ax.set_ylim'};
  const call=specific[lesson.id] || r.solution.match(/sns\.\w+(?=\()/)?.[0];
  if(call)r.starter=r.solution.replace(call,call.split('.')[0]+'.____');
  if(lesson.id==='V30')r.starter=r.solution.replace('bottom=first','bottom=____');
 } else if(!r.starter.includes('____')) {
  const call=r.solution.match(/\b(?:df|pd|np)\.\w+(?=\()/)?.[0];
  if(call)r.starter=r.solution.replace(call,call.split('.')[0]+'.____');
  else if(r.solution.startsWith('df[') && r.solution.includes(' = '))r.starter=r.solution.replace(/ = [^\n]+/, ' = ____');
  else if(r.solution.startsWith('df.iloc'))r.starter=r.solution.replace(/:\d+/, ':____');
  else r.starter='# Complete the expression using the worked example\n____';
 }
}
const curriculum={version:1,datasets,decks,lessons:ordered,setupCode};
(typeof module!=='undefined'?require('./refinements.js'):root.refineFoundations)(curriculum);
(typeof module!=='undefined'?require('./progression.js'):root.progressFoundations)(curriculum);
(typeof module!=='undefined'?require('./clarity.js'):root.FoundationClarity).clarify(curriculum);
if(typeof module!=='undefined')module.exports=curriculum;
else root.FoundationsCurriculum=curriculum;
})(typeof window!=='undefined'?window:globalThis);
