/* Practical revisions: produce a useful artifact, using introduced skills. */
(function(root){
'use strict';
function practical(c){
 const get=id=>c.lessons.find(l=>l.id===id), D=c.datasets;
 function task(id,i,text,code,hint,options={}){
  const r=get(id).rounds[i];
  Object.assign(r,{task:text,solution:code,hint,target:'value',plot:null,resultKind:'value',requiredCalls:[],requiredKeywords:[],forbiddenCalls:[],strictDtype:false,preserveData:false,reflection:null,bridge:null,demand:i===0?'Follow the technique':i===1?'Adapt the workflow':'Combine earlier skills',...options});
  if(i===0)r.starter='# Complete the requested operation\n____';
  if(options.bridge)get(id).tools.push(options.bridge);
 }
 function figure(id,i,text,body,x,y,options={}){
  const d=D[get(id).rounds[i].dataset],title=options.title||d.name;
  task(id,i,text+` Use title "${title}", x label "${x}" and y label "${y}". Finish with fig.tight_layout() and display with plt.show().`,
   `import matplotlib.pyplot as plt\nimport seaborn as sns\n\nfig, ax = plt.subplots(figsize=(6, 4))\n${body}\nax.set(title="${title}", xlabel="${x}", ylabel="${y}")\nfig.tight_layout()\nplt.show()`,
   options.hint||'Choose the observations first, then map the requested measurements to the chart.',{target:'plot',resultKind:'Figure',plot:options.plot||{},...options});
 }
 // Introduce previewing before file import, so importing + inspecting is retrieval.
 const csv=get('I01CSV');c.lessons.splice(c.lessons.indexOf(csv),1);c.lessons.splice(c.lessons.indexOf(get('I02'))+1,0,csv);
 for(const [i,key] of ['candy','cafe','pets'].entries()){
  const r=csv.rounds[i];r.dataset=key;r.files={[key+'.csv']:D[key].columns};
 }
 task('I01CSV',0,'Load the supplied candy.csv into df and display the imported table. Practise: read_csv().','import pandas as pd\n\ndf = pd.read_csv("candy.csv")\ndf','read_csv returns a DataFrame; assign it before displaying it.',{requiredCalls:['read_csv']});
 task('I01CSV',1,'The supplied cafe.csv uses semicolons between fields. Load it into df with the correct separator and display the table with its columns kept separate.', 'import pandas as pd\n\ndf = pd.read_csv("cafe.csv", sep=";")\ndf', 'Check the file preview: the separator is a semicolon, not the default comma.');
 csv.rounds[1].files={'cafe.csv':Object.keys(D.cafe.columns).join(';')+'\n'+D.cafe.columns.drink.map((_,i)=>Object.values(D.cafe.columns).map(values=>values[i]).join(';')).join('\n')};
 task('I01CSV',2,'A colleague sent the supplied pets.csv. Load it into a DataFrame and display the first five rows as an intake check.','import pandas as pd\n\npets = pd.read_csv("pets.csv")\npets.head()','Use the import skill with the earlier first-rows inspection skill.');
 csv.tools=['pd.read_csv(path, sep=";") reads a semicolon-delimited file; the default separator is a comma.', 'The files in these exercises contain six records. head() displays five rows without removing the sixth from the loaded table.'];
 csv.goal='Load a file and inspect what arrived.';
 csv.explanation+=' After loading, use head() or tail() from the previous lesson to inspect records before analysis.';
 // First construction: an actual reporting requirement, not a variable-name puzzle.
 task('I01',1,'The supplied café table is going to an accounts colleague. Build df with price first and drink second, keeping every row. Display df.','import pandas as pd\n\ndata = {"price": [6.2, 3.1, 6.8, 2.5], "drink": ["Latte", "Tea", "Mocha", "Espresso"]}\ndf = pd.DataFrame(data)\ndf','Dictionary keys determine the initial column order.',{target:'df'});
 const pet=get('I01').rounds[2];
 pet.setup='names = ["Milo", "Pepper", "Luna", "Bean"]\nages = [3, 7, 2, 4]';
 task('I01',2,'A shelter supplied separate lists named names and ages in the setup code. Build df with columns name and age, pairing items in their supplied order. Display the intake table.','import pandas as pd\n\ndata = {"name": names, "age": ages}\ndf = pd.DataFrame(data)\ndf','Use the supplied lists as dictionary values; each position represents the same pet.',{target:'df'});
 task('I03',1,'The import log says the supplied df should contain six orders. Calculate and display its row count to reconcile it with the log.','len(df)','len counts records; shape describes both dimensions.');
 const shape=get('I03').rounds[2];shape.files={'pets.csv':D.pets.columns};
 task('I03',2,'Load the supplied pets.csv and check its dimensions before preparing a report. Display the complete table’s (rows, columns) pair, not the shape of a preview.','import pandas as pd\n\ndf = pd.read_csv("pets.csv")\ndf.shape','Inspect the loaded table itself; head() would reduce the row count.');
 task('I04',2,'A new supplied pets.csv needs a schema check before analysis. Load it into df, then display its column names in file order as a list.','import pandas as pd\n\ndf = pd.read_csv("pets.csv")\nlist(df.columns)','Read the actual names rather than guessing from the dataset description.');
 get('I04').rounds[2].files={'pets.csv':D.pets.columns};
 task('I05',1,'Before a quick café import check, take the first three records of df and display their dtypes. This checks column types, not whether every value is valid.','preview = df.head(3)\npreview.dtypes','Use dtypes for a returned result; info() prints its overview.');
 task('I05',2,'Load the supplied pets.csv and display a dtype for every imported column. Keep all records available for later inspection.','import pandas as pd\n\ndf = pd.read_csv("pets.csv")\ndf.dtypes','Combine importing with a schema check; do not narrow the table first.');
 get('I05').rounds[2].files={'pets.csv':D.pets.columns};get('I05').tools=[];
 task('I14',2,'The shelter needs the species represented among pets aged at least 3 in df. Display the distinct species as a list, in first-appearance order.','eligible = df[df["age"] >= 3]\nlist(eligible["species"].unique())','Choose the report population before listing its categories.');
 task('I21',2,'For games lasting at least 20 minutes in df, inspect the linear association between minutes and rating. Display their correlation matrix in that column order.','selected = df[df["minutes"] >= 20]\nselected[["minutes", "rating"]].corr()','Filter whole records so each pair stays together.',{reflection:'What does the sign suggest? Explain why this small observational sample cannot establish causation.'});
 task('W01',0,'Prepare a separate price-list copy named clean from df. Keep candy and price in that order; leave the original df intact and display clean. Practise: copy().','clean = df.copy()\nclean = clean[["candy", "price"]]\nclean','Make the copy before preparing the handoff.',{target:'copy',requiredCalls:['copy']});
 task('W01',1,'Prepare a separate clean copy of the supplied café df for a price review. Keep every column and sort whole rows by price, highest first. Preserve df and display clean.','clean = df.copy()\nclean = clean.sort_values("price", ascending=False)\nclean','Sorting the copy must not reorder the original.',{target:'copy'});
 task('W02',1,'The accounts export uses explicit currency labels. In df rename price to price_dollars and tip to tip_dollars. Preserve rows and column order; display df.','df = df.rename(columns={"price": "price_dollars", "tip": "tip_dollars"})\ndf','Map existing names to the export schema.',{target:'df'});
 task('W02',2,'Prepare a two-column shelter handoff from df: name, then age renamed age_years. Display the handoff as df.','df = df[["name", "age"]].rename(columns={"age": "age_years"})\ndf','Use a label that communicates the measurement and unit.',{target:'df'});
 task('W07',0,'The shop offers a two-item pack of each candy. Using df unit prices, add pair_price equal to twice price. Keep the original columns and display df.','df["pair_price"] = df["price"] * 2\ndf','A two-item pack costs two unit prices under this offer.',{target:'df'});
 task('W09',0,'The supplied catalogue df is adopting the label fruit in place of fruity. Update flavour while retaining all other labels and columns; display df. Practise: replace().','df["flavour"] = df["flavour"].replace({"fruity": "fruit"})\ndf','replace updates the named category without erasing the others.',{target:'df',requiredCalls:['replace']});
 task('W09',2,'Prepare a separate clean copy of df for a shelter system that uses Feline and Canine instead of Cat and Dog. Recode species, preserving Rabbit and the original df. Display clean.','clean = df.copy()\nclean["species"] = clean["species"].replace({"Cat": "Feline", "Dog": "Canine"})\nclean','Use a recoding method that preserves labels absent from the mapping.',{target:'copy'});
 task('W22',2,'A shelter chart compares age and weight for pets aged at least 2 in df. Filter those records and reshape both measurements into columns name, measure, value. Keep age before weight.','selected = df[df["age"] >= 2]\nselected.melt(id_vars=["name"], value_vars=["age", "weight"], var_name="measure", value_name="value")','Keep the measure column so values with different units remain distinguishable.');
 task('W25',1,'Two supplied café batches have the same schema. Combine first then second, retaining their original row labels so an import audit can trace each batch’s positions. Each batch starts its row labels at zero; repeated labels are expected in this intermediate result. Display the combined table.','pd.concat([first, second])','ignore_index discards source labels; omit it when those labels are needed.');
 get('W25').rounds[1].setup='first = df.iloc[:3].copy().reset_index(drop=True)\nsecond = df.iloc[3:].copy().reset_index(drop=True)';
 task('W29',2,'Prepare a review list from df: find ages beyond either 1.5×IQR fence, select those records, then display name and age sorted oldest first. Preserve df; a flag is not permission to delete a record.','q1 = df["age"].quantile(0.25)\nq3 = df["age"].quantile(0.75)\niqr = q3 - q1\nflagged = df[(df["age"] < q1 - 1.5 * iqr) | (df["age"] > q3 + 1.5 * iqr)]\nflagged[["name", "age"]].sort_values("age", ascending=False)','Separate detection, record selection and presentation.',{preserveData:true,reflection:'What source information would you check before correcting or excluding a flagged age?'});
 task('W30',0,'A price revision raises all unit prices in df by 10%. Add adjusted as the revised price rounded to two decimals, preserving the original price. Display df. Use vectorised arithmetic; do not use apply().','df["adjusted"] = (df["price"] * 1.1).round(2)\ndf','Keep raw and revised prices side by side.',{target:'df',forbiddenCalls:['apply']});
 // Canvas exercises produce canvases. Interpretation stays beside the artifact.
 figure('V01',1,'Prepare one empty Figure for a wide report about df. Use figsize=(8, 4), with one Axes.', '', 'temperature','humidity',{plot:{empty:true,size:true},title:'Weather overview'});
 get('V01').rounds[1].solution=get('V01').rounds[1].solution.replace('figsize=(6, 4)','figsize=(8, 4)');
 figure('V01',2,'Prepare one empty square Figure for a report about df playing time and ratings. Use figsize=(5, 5), with one Axes.', '', 'Minutes','Rating',{plot:{empty:true,size:true},title:'Game comparison'});
 get('V01').rounds[2].solution=get('V01').rounds[2].solution.replace('figsize=(6, 4)','figsize=(5, 5)');
 get('V01').tools=['figsize=(width, height) sizes the canvas in inches. ax.set(title=..., xlabel=..., ylabel=...) names the question and axes. Multi-panel layouts come later.'];
 for(const id of ['V10','V12','V14'])get(id).rounds[2].dataset='games';
 // One channel at a time before redundant encodings in V17.
 figure('V03',0,'Using df, compare hours and score with club mapped to colour. Keep point sizes and marker shapes constant. Practise: scatterplot().','sns.scatterplot(data=df, x="hours", y="score", hue="club", ax=ax)','hours','score',{requiredCalls:['scatterplot'],plot:{colors:true,legend:true}});
 figure('V03',2,'For df games lasting at least 20 minutes, compare minutes and rating with genre mapped to colour. Keep point sizes and shapes constant.','selected = df[df["minutes"] >= 20]\nsns.scatterplot(data=selected, x="minutes", y="rating", hue="genre", ax=ax)','minutes','rating',{plot:{colors:true,legend:true}});
 get('V03').goal='Use colour to compare categories in a scatter chart.';get('V03').syntaxCode='sns.scatterplot(data=df, x="hours", y="score", hue="club", ax=ax)';
 figure('V05',2,'For df games lasting at least 20 minutes, inspect the distribution of minutes using a KDE with cut=0 and bw_adjust=1. Treat its shape as exploratory.','selected = df[df["minutes"] >= 20]\nsns.kdeplot(data=selected, x="minutes", cut=0, bw_adjust=1, ax=ax)','minutes','Density',{reflection:'Would these few observations justify a claim about the population’s modes?'});
 figure('V06',2,'A club needs to see what fraction of df games finish within each duration. Display an ECDF of minutes for games rated at least 4.','selected = df[df["rating"] >= 4]\nsns.ecdfplot(data=selected, x="minutes", ax=ax)','minutes','Proportion',{reflection:'Read the fraction finishing within 35 minutes from the chart.'});
 figure('V07',2,'For df games rated at least 4, show a four-bin histogram of minutes with rug marks on the same Axes so individual durations remain visible.','selected = df[df["rating"] >= 4]\nsns.histplot(data=selected, x="minutes", bins=4, ax=ax)\nsns.rugplot(data=selected, x="minutes", ax=ax)','minutes','Count');
 figure('V10',2,'Compare mean game rating by genre in df. Use point estimates with one-standard-deviation error bars and capsize=0.15. Keep categories in first-appearance order.','sns.pointplot(data=df, x="genre", y="rating", errorbar="sd", capsize=0.15, ax=ax)','genre','Mean rating',{reflection:'The bars describe observation spread, not confidence intervals.'});
 figure('V12',2,'For df games lasting at least 20 minutes, compare ratings by genre with violins, cut=0 and inner="point". Keep categories in first-appearance order and inspect the raw points before interpreting the smooth shape.','selected = df[df["minutes"] >= 20]\nsns.violinplot(data=selected, x="genre", y="rating", cut=0, inner="point", ax=ax)','genre','rating');
 figure('V14',2,'For df games lasting at least 20 minutes, show individual ratings by genre with a swarm plot. Keep categories in first-appearance order.','selected = df[df["minutes"] >= 20]\nsns.swarmplot(data=selected, x="genre", y="rating", size=5, ax=ax)','genre','rating');
 // A tiny table should not be used to teach inference from estimated tails.
 get('V15').title='Choose detail to suit the sample';get('V15').goal='Prefer observed points when groups are too small for tail summaries.';
 get('V15').explanation='Letter-value plots show nested quantile bands and suit larger groups. With these tiny groups, plot the actual observations instead. More elaborate graphics cannot create information that the sample does not contain.';
 get('V15').syntax=[['sns.stripplot(..., jitter=False)','show raw observations at their category positions'],['sns.boxplot(...)','summarise the same observations with a box'],['sns.boxenplot(...)','nested quantiles for larger samples; not needed for this tiny table']];
 get('V15').syntaxCode='sns.stripplot(data=df, x="flavour", y="price", jitter=False, ax=ax)';get('V15').tools=[];
 figure('V15',0,'Using df, inspect every price by flavour with a strip plot and jitter=False. The catalogue is too small to justify detailed tail estimates. Practise: stripplot().','sns.stripplot(data=df, x="flavour", y="price", jitter=False, ax=ax)','flavour','price',{requiredCalls:['stripplot']});
 figure('V15',1,'Compare humidity by sky in df using horizontal raw points with jitter=False. Map humidity to x and sky to y.','sns.stripplot(data=df, x="humidity", y="sky", jitter=False, ax=ax)','humidity','sky');
 figure('V15',2,'A shelter has only two pets per species in df. Show every weight by species with raw points and jitter=False, rather than estimating tail shapes.','sns.stripplot(data=df, x="species", y="weight", jitter=False, ax=ax)','species','weight');
 figure('V19',2,'From the supplied repeated df visits, show replicate B over day as a line with markers and no aggregation. This report follows one replicate, not a mean across replicates.','selected = df[df["replicate"] == "B"]\nsns.lineplot(data=selected, x="day", y="visits", estimator=None, marker="o", ax=ax)','day','visits');
 figure('V20',2,'For df games lasting at least 20 minutes, inspect a linear trend of rating against minutes with the observations and no confidence band.','selected = df[df["minutes"] >= 20]\nsns.regplot(data=selected, x="minutes", y="rating", ci=None, ax=ax)','minutes','rating',{reflection:'Explain why a fitted association does not establish that longer games cause higher ratings.'});
 figure('V21',2,'For df games lasting at least 20 minutes, inspect residuals of a linear rating-versus-minutes fit. Keep minutes on x.','selected = df[df["minutes"] >= 20]\nsns.residplot(data=selected, x="minutes", y="rating", ax=ax)','minutes','Residual',{reflection:'Look for structure around zero; a tiny sample cannot establish model adequacy.'});
 D.load_test={name:'Service load test',columns:{requests:[10,30,100,300,1000,3000],response_ms:[35,37,42,60,110,240]},a:'requests',b:'response_ms',id:'requests',c:'requests',d:'requests'};
 get('V26').rounds[0].dataset='load_test';
 figure('V26',0,'The supplied df spans several orders of magnitude in request count. Plot requests against response_ms on a logarithmic x-axis and a linear y-axis starting at zero. Rotate x tick labels by 30 degrees. Practise: set_xscale().','sns.scatterplot(data=df, x="requests", y="response_ms", ax=ax)\nax.set_xscale("log")\nax.set_ylim(bottom=0)\nax.tick_params(axis="x", labelrotation=30)','Requests','Response time (ms)',{requiredCalls:['set_xscale'],plot:{limits:true,ticks:true}});
 get('V26').syntaxCode='ax.set_xscale("log")\nax.set_ylim(bottom=0)';
 figure('V26',1,'Prepare the supplied df weather chart for a dashboard using common panel scales: temperature from 20 to 35 °C and humidity from 0 to 100%. Retain all observations.','sns.scatterplot(data=df, x="temperature", y="humidity", ax=ax)\nax.set_xlim(20, 35)\nax.set_ylim(0, 100)','Temperature (°C)','Humidity (%)',{plot:{limits:true}});
 figure('V26',2,'Compare minutes and rating for every game in df on linear axes. Keep the full dataset visible; set the rating axis from 0 to 5, its stated scale.','sns.scatterplot(data=df, x="minutes", y="rating", ax=ax)\nax.set_ylim(0, 5)','minutes','Rating (0–5)',{plot:{limits:true},bridge:'ax.set_ylim(lower, upper) sets both ends of the y-axis. Choose limits that retain the observations.'});
 figure('V29',0,'Using df, calculate mean price by flavour in alphabetical order, then draw those exact values as bars. This compares catalogue prices, not sales revenue. Practise: bar().','means = df.groupby("flavour")["price"].mean()\nax.bar(means.index, means.values)','flavour','Mean price',{requiredCalls:['bar'],plot:{categorical:true,semantic:'bars'}});
 figure('V30',2,'The supplied df contains Online and Shop counts. Compare Shop counts across items using bars with a common zero baseline, in table order.','ax.bar(df["item"], df["Shop"])\nax.set_ylim(bottom=0)','item','Shop count',{plot:{semantic:'bars',categorical:true,zeroBaseline:true},reflection:'Why is this easier to compare precisely than Shop segments stacked above varying Online counts?'});
 const imports='import matplotlib.pyplot as plt\nimport seaborn as sns\n\n';
 task('V31',2,'For df games lasting at least 20 minutes, create a pairplot of minutes and rating, with histogram diagonals and no hue grouping. Finish g.figure with tight_layout() and display with plt.show().',imports+'selected = df[df["minutes"] >= 20]\ng = sns.pairplot(data=selected, vars=["minutes", "rating"], diag_kind="hist")\ng.figure.tight_layout()\nplt.show()','Select the population and variables before creating the grid.',{target:'plot',plot:{},resultKind:'Figure'});
 task('V32',2,'For df games lasting at least 20 minutes, create a joint scatter of minutes against rating. Add a dashed horizontal line at rating 4 to the central Axes only. Finish g.figure with tight_layout() and display with plt.show().',imports+'selected = df[df["minutes"] >= 20]\ng = sns.jointplot(data=selected, x="minutes", y="rating", kind="scatter")\ng.ax_joint.axhline(4, linestyle="--")\ng.figure.tight_layout()\nplt.show()','The reference belongs to the relationship panel, not either marginal distribution.',{target:'plot',plot:{},resultKind:'Figure'});
 figure('V34',2,'For df games lasting at least 20 minutes, make a minutes-versus-rating scatter for a report. Save chart.png at 150 dpi with bbox_inches="tight" before displaying.','selected = df[df["minutes"] >= 20]\nax.scatter(selected["minutes"], selected["rating"])','minutes','rating',{plot:{semantic:'scatter',export:true}});
 get('V34').rounds[2].solution=get('V34').rounds[2].solution.replace('plt.show()','fig.savefig("chart.png", dpi=150, bbox_inches="tight")\nplt.show()');
 figure('V36',0,'Using df, compare mean price by flavour as bars, highest mean first. Start the y-axis at zero so lengths represent the price comparison fairly. Practise: bar().','means = df.groupby("flavour")["price"].mean().sort_values(ascending=False)\nax.bar(means.index, means.values)\nax.set_ylim(bottom=0)','flavour','Mean price',{requiredCalls:['bar'],plot:{semantic:'bars',categorical:true,zeroBaseline:true}});
 figure('V36',2,'A shelter report compares average weight by species in df. Show exact bars ordered alphabetically with a zero baseline, preserving the actual differences.','means = df.groupby("species")["weight"].mean()\nax.bar(means.index, means.values)\nax.set_ylim(bottom=0)','species','Mean weight',{plot:{semantic:'bars',categorical:true,zeroBaseline:true}});
 // Checkpoints have distinct reporting constraints, rather than three renamed recipes.
 task('W31',1,'Prepare clean as a separate copy of the supplied game orders df. Remove confirmed exact duplicate rows. Trim and lowercase game, replacing literal hyphens with spaces; trim and title-case edition. Preserve raw price and add numeric_price with invalid text coerced to missing. Parse date with year-month-day format, preserving invalid dates as NaT. Keep only records with a known numeric_price, sort by order and reset the index. Leave df intact and display clean.',
  'clean = df.copy().drop_duplicates()\nclean["game"] = clean["game"].str.strip().str.lower().str.replace("-", " ", regex=False)\nclean["edition"] = clean["edition"].str.strip().str.title()\nclean["numeric_price"] = pd.to_numeric(clean["price"], errors="coerce")\nclean["date"] = pd.to_datetime(clean["date"], format="%Y-%m-%d", errors="coerce")\nclean = clean.dropna(subset=["numeric_price"]).sort_values("order").reset_index(drop=True)\nclean',
  'Preserve the raw price before parsing; eligibility depends on numeric_price only.',{target:'copy'});
 task('W31',2,'Prepare a billing table clean from the supplied pet-supply orders df, preserving df. Remove confirmed exact duplicate rows. Trim and lowercase item and trim and title-case package. Parse price as numeric, then retain rows with known numeric prices. For this billing export a missing discount means no discount; fill it with zero. Both price and discount use the same currency. Add net_price as price minus discount. Display only order, item, package and net_price, sorted by order with a fresh consecutive index.',
  'clean = df.copy().drop_duplicates()\nclean["item"] = clean["item"].str.strip().str.lower()\nclean["package"] = clean["package"].str.strip().str.title()\nclean["price"] = pd.to_numeric(clean["price"], errors="coerce")\nclean = clean.dropna(subset=["price"])\nclean["discount"] = clean["discount"].fillna(0)\nclean["net_price"] = clean["price"] - clean["discount"]\nclean = clean[["order", "item", "package", "net_price"]].sort_values("order").reset_index(drop=True)\nclean',
  'Use the stated meaning of missing discount. Filter invalid prices before calculating the billed amount.',{target:'copy'});
 get('W31').explanation='Combine the earlier cleaning tools into a usable handoff. Each task has its own rules for required fields, unknown values and output columns. Preserve the source table and apply only the policy stated in that task.';
 // Canvas creation is a small concept: practise it once, then reuse it in real charts.
 get('V01').rounds=get('V01').rounds.slice(0,1);get('V01').minutes=4;
 get('W07').syntaxCode='df["pair_price"] = df["price"] * 2';
 get('W09').syntaxCode='df["flavour"] = df["flavour"].replace({"fruity": "fruit"})';
 // Follow retains a focused completion scaffold rather than an empty editor.
 get('I01CSV').rounds[0].starter='import pandas as pd\n\ndf = pd.____("candy.csv")\ndf';
 const scaffolds={W01:['df.copy()','df.____()'],W07:['* 2','* ____'],W09:['.replace(','.____('],W30:['* 1.1','* ____'],V03:['hue="club"','hue=____'],V15:['sns.stripplot(','sns.____('],V26:['ax.set_xscale("log")','ax.set_xscale(____)'],V29:['ax.bar(','ax.____('],V36:['ax.set_ylim(bottom=0)','ax.set_ylim(bottom=____)']};
 for(const [id,[from,to]] of Object.entries(scaffolds))get(id).rounds[0].starter=get(id).rounds[0].solution.replace(from,to);
 // Minimise duplicated finish instructions introduced by earlier content migrations.
 for(const l of c.lessons)for(const r of l.rounds){
  if(/\bnp\./.test(r.solution)&&!r.solution.includes('import numpy'))r.solution='import numpy as np\n\n'+r.solution;
  r.task=r.task.replace('Finish with fig.tight_layout() and plt.show(). Display the chart with plt.show().','Finish with fig.tight_layout() and plt.show().').replace('Finish with tight_layout and show. Display the chart with plt.show().','Finish with fig.tight_layout() and plt.show().');
 }
 return c;
}
if(typeof module!=='undefined')module.exports=practical;else root.practicalFoundations=practical;
})(typeof window!=='undefined'?window:globalThis);
