import assert from 'node:assert/strict';
import worker from '../cloudflare/private-worker.mjs';
const host = 'https://private.dataplayground.science';
const owner = {access:{getIdentity:async()=>({email:'elijahang77@gmail.com'})}};
const req = path => new Request(host + path);
assert.equal((await worker.fetch(req('/'), {}, {})).status,403);
assert.equal((await worker.fetch(req('/'), {}, {access:{getIdentity:async()=>({email:'other@example.com'})}})).status,403);
assert.equal((await worker.fetch(req('/'), {}, {access:{getIdentity:async()=>{throw Error();}}})).status,503);
assert.equal((await worker.fetch(new Request('https://evil.example/'),{},owner)).status,404);
assert.equal((await worker.fetch(new Request(host,{method:'POST',body:'secret'}),{},owner)).status,405);
const ad = await worker.fetch(req('/ad-mode.js?ads=on'),{},owner);
assert.match(await ad.text(),/canLoadAdvertising:\(\)=>false/);
assert.equal(ad.headers.get('cache-control'),'private, no-store');
assert.equal((await worker.fetch(req('/ads.txt'),{},owner)).status,404);
assert.match(await (await worker.fetch(req('/service-worker.js'),{},owner)).text(),/unregister/);
const originalFetch = globalThis.fetch;
let outgoing;
globalThis.fetch = async (url,opts) => {
  outgoing={url:String(url),opts};
  return new Response('dataset', {headers:{'content-type':'text/csv'}});
};
const result=await worker.fetch(new Request(host+'/data.csv?ads=on&adpreview=footer',{headers:{cookie:'private',authorization:'secret','cf-access-jwt-assertion':'secret'}}),{},owner);
assert.equal(await result.text(),'dataset');
assert.equal(outgoing.url,'https://dataplayground.science/data.csv');
assert.deepEqual(outgoing.opts.headers,{accept:'*/*'});
globalThis.fetch=async()=>new Response(null,{status:301,headers:{location:'https://evil.example/'}});
assert.equal((await worker.fetch(req('/'),{},owner)).status,502);
globalThis.fetch=async()=>new Response(null,{status:301,headers:{location:'https://dataplayground.science/index.html'}});
assert.equal((await worker.fetch(req('/'),{},owner)).headers.get('location'),host+'/index.html');
globalThis.fetch=originalFetch;
console.log('Private Worker security and proxy tests passed');
