"""Regenerate readable Python examples: python -m pip install black==25.1.0.

Author curriculum JS normally, then run this script (or --check in maintenance).
The committed adapter lets direct-file previews use identical formatted code.
Only whitespace/quote formatting is allowed: every AST must remain unchanged.
"""
import argparse
import ast
import json
import os
from pathlib import Path
import subprocess
import black

ROOT = Path(__file__).resolve().parents[1]
parser = argparse.ArgumentParser()
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
c = json.loads(subprocess.check_output(
    ['node', '-e', 'const c=require("./foundations/curriculum.js"); console.log(JSON.stringify({lessons:c.lessons,setups:Object.keys(c.datasets).map(k=>c.setupCode(k))}));'],
    cwd=ROOT, env={**os.environ, 'FOUNDATIONS_RAW_CODE': '1'}, text=True))
fields = ['solution', 'starter', 'setup', 'example', 'syntaxCode']
sources = list(c['setups'])
for lesson in c['lessons']:
    for item in [lesson, *lesson['rounds']]:
        sources.extend(item[field] for field in fields if item.get(field))

def format_code(code):
    tree = ast.parse(code)
    lines = code.splitlines(keepends=True)
    changes = []
    for node in ast.walk(tree):
        if isinstance(node, ast.Dict) and len(node.keys) > 1:
            # A trailing comma asks Black to put dictionary entries on separate lines.
            end = sum(len(line) for line in lines[:node.end_lineno - 1])
            end += len(lines[node.end_lineno - 1].encode()[:node.end_col_offset].decode()) - 1
            if code[:end].rstrip().endswith(','):
                continue
            changes.append((end, ','))
    for at, text in sorted(changes, reverse=True):
        code = code[:at] + text + code[at:]
    formatted = black.format_str(code, mode=black.Mode(line_length=88))
    # Keep the import block visually separate from the first operation.
    formatted = __import__('re').sub(r'((?:^import .+\n|^from .+ import .+\n)+)(?!import |from )(?=\S)', r'\1\n', formatted, flags=__import__('re').M)
    assert ast.dump(tree) == ast.dump(ast.parse(formatted)), code
    return formatted.rstrip() + ('\n' if code.endswith('\n') else '')

mapping = {}
for code in sorted(set(sources)):
    if not code.strip():
        continue
    formatted = format_code(code)
    if code != formatted:
        mapping[code] = formatted
payload = '''/* Generated by scripts/format-foundations.py with Black 25.1.0; do not edit. */
(function(root){
const formatted = ''' + json.dumps(mapping, ensure_ascii=False, indent=2) + ''';
function style(c){
 const format=code=>formatted[code]||code;
 for(const lesson of c.lessons)for(const item of [lesson,...lesson.rounds])
  for(const field of ['solution','starter','setup','example','syntaxCode'])if(item[field])item[field]=format(item[field]);
 const setup=c.setupCode;c.setupCode=key=>format(setup(key));
 return c;
}
if(typeof module!=='undefined')module.exports=style;else root.styleFoundationsCode=style;
})(typeof window!=='undefined'?window:globalThis);
'''
target = ROOT / 'foundations/code-style.js'
if args.check:
    assert target.read_text() == payload, 'Run scripts/format-foundations.py to update examples.'
else:
    target.write_text(payload)
print(f'Consistent Python formatting: {len(set(sources))} snippets checked; {len(mapping)} formatted without AST changes.')
