"""Consistent family lenses layered on the existing small examples and diagrams."""
GUIDES={
 'simple_linear':('Simple linear regression','How does one available measurement help predict a quantity?','A slope and intercept minimise squared training residuals.','Curvature, unusual points and extrapolation can make a straight line misleading.','Read the residuals: does a curve remain? Explain why a small training error does not establish performance beyond the observed input range.'),
 'multiple_linear':('Multiple linear regression','How do several available inputs jointly predict a quantity?','One coefficient per prepared input adds to an intercept.','Correlated inputs destabilise individual coefficients; coefficients do not establish causes.','Explain what holding other inputs fixed means. Would two near-duplicate inputs change coefficient interpretation even if predictions barely change?'),
 'polynomial':('Polynomial regression','Does a smooth curve improve quantity prediction?','Expand powers of the inputs, then fit the regularised linear recipe.','Higher degree can follow noise; extrapolated curves can diverge rapidly.','Compare degrees using training folds. A lower training error alone is not a reason to increase degree.'),
 'regression_tree':('Regression tree','Can threshold rules predict a quantity?','Repeated feature cuts form leaves that predict training averages.','Deep leaves overfit small samples; predictions cannot smoothly extrapolate beyond learned leaves.','Compare training and validation errors and inspect a poorly populated leaf. Explain when a shallower tree is preferable.'),
 'logistic':('Logistic classification','Which class is plausible from available inputs?','A linear score becomes class probabilities and then a decision.','A linear boundary can miss curved separation; probability and decision cost are different.','Explain which error changes when the decision threshold moves, and why threshold selection belongs inside training validation.'),
 'svm_cls':('Support vector classification','Can a margin separate classes in the prepared feature space?','Support vectors define a margin; a kernel can make the boundary curved.','Unscaled inputs distort geometry; a flexible kernel can overfit.','Compare a linear and curved boundary using matching folds. Explain why a perfect training score is insufficient.'),
 'one_r':('One-R classification','How well can one input alone assign a class?','Learn one feature’s category or interval rule and choose it using training evidence.','Interactions are ignored; rare categories or unstable cut points can mislead.','Inspect which feature won. Explain why a rule learned before the split leaks information even if the final classifier uses only one feature.'),
 'classification_tree':('Classification tree','Can a short sequence of conditions predict a class?','Each split concentrates class labels; leaves predict class evidence.','Tiny leaves memorise observations; class imbalance can hide rare-class failures.','Inspect minority-class validation errors and depth. Repair overfitting using training-only evidence.'),
 'knn_cls':('Nearest neighbours','Do nearby measured examples suggest a label?','Scaled distances identify neighbours whose class labels vote.','Units and irrelevant features change neighbourhoods; small k can be noisy.','If a measurement changes units, explain why the unscaled prediction can change. Compare k with a fold-local scaler.'),
 'naive_bayes':('Naive Bayes','Which class best explains these measurements or flags?','Combine feature likelihoods under conditional independence and class priors.','Correlated evidence can be counted twice; continuous and binary features need appropriate likelihoods.','Identify whether Gaussian or Bernoulli assumptions match the input. Explain why correlated indicators can create overconfident evidence.'),
 'lda':('Linear discriminant analysis','Can class means and shared variation separate labels?','Use class means with a shared within-class covariance to form linear boundaries.','Different covariance shapes or redundant inputs can undermine the model.','Compare class spreads before defending a shared covariance. Use validation to test the modelling simplification.'),
 'qda':('Quadratic discriminant analysis','Do classes need different covariance shapes?','Estimate a covariance per class to form curved boundaries.','Many covariance parameters need enough examples per class; singular fits are unstable.','Explain why flexibility may hurt a small rare class and compare the simpler shared-covariance alternative.'),
 'mlp_cls':('Neural classification','Can learned nonlinear combinations improve class prediction?','Hidden units transform scaled inputs; an output layer represents class evidence.','Convergence, scale, random initialisation and overfitting require diagnosis.','Inspect loss and validation evidence together. A falling training loss alone does not prove useful predictions.'),
 'mlp_reg':('Neural regression','Can learned nonlinear combinations predict a quantity?','Hidden units transform scaled features; the target wrapper returns predictions in original units.','Unstable optimisation and overfitting can dominate small datasets.','Check original target units and loss history, then compare a simple baseline on matching folds.'),
 'kmeans':('K-Means','What compact groups describe these observations?','Alternate nearest-centre assignments and mean-centre updates in scaled space.','Round distance-based groups may not reflect useful categories; k is a resolution choice.','Compare silhouette, sizes and original-unit profiles. Explain why reference labels must stay outside fitting and why no final classification accuracy is claimed.'),
 'hierarchical':('Hierarchical clustering','How do observations merge into groups at different resolutions?','Ward merges groups to limit increases in within-group squared variation.','Scale, unusual points and sampling change merges; a cut does not discover a uniquely true class.','Read merge heights and compare two cuts. Explain how the sample limits the scope of group profiles.'),
 'pca':('Principal component analysis','Can fewer axes summarise variation in the measurements?','Orthogonal combinations successively retain as much variance as possible.','High variance need not be useful for prediction; unscaled units can dominate.','Read weights and retained variance together. Explain why a component is a combination rather than an original feature, and why PCA is neither a target predictor nor a cluster label.'),
}

def apply(registry):
    for card in registry['cards']:
        if card['kind']!='teaching':continue
        card['modelGuide']=[]
        for id in card['models']:
            name,question,mechanism,failure,debug=GUIDES[id]
            card['modelGuide'].append(dict(name=name,question=question,mechanism=mechanism,failure=failure,debug=debug,challenges=[c['id'] for c in registry['challenges'] if id in c['models']]))
    return registry
