"""Context shifts that require a decision, beyond repeating an API on new columns."""
from authoring import reflect
# Complete the previously two-round lessons without replacing their existing IDs.
ADDITIONS={
 'F01':('A library wants to allocate staff. Compare predicting next-hour arrivals, grouping branches by usage, and compressing correlated usage measures. Specify whether X/y exist and name the Python objects you would prepare for each.', 'Prediction needs historical arrival outcomes y aligned to available X. Grouping uses a feature dataframe without a target. PCA also has no y but creates new coordinates rather than groups. Ask whether the team needs a forecast, a segmentation or a compact representation before selecting a method.'),
 'F03':('A fitted delivery model is reused for a second city with different traffic. Would calling predict on the new city learn its traffic pattern? Explain which Python call changes coefficients and what evidence is needed before trusting a refit.', 'predict reuses the old coefficients; fit estimates new coefficients from labelled training data. A refit on new-city training rows must still be evaluated on held-away rows representing the intended use. Neither executing fit nor finding a new slope establishes that the model generalises.'),
 'F06':('A handwriting classifier gets 99% on training images and 62% on validation images from unseen writers. Propose a repair and explain why splitting images randomly across the same writers may answer an easier question.', 'The gap suggests poor generalisation. Simplify or regularise using training validation; inspect writer differences and input quality. Keep writers disjoint if the intended use is new writers. Random image splitting may leak writer-specific information and overstate performance on unfamiliar writers.'),
 'F08':('A hospital stores ward names as 1, 2 and 3. A transport table stores trip duration as whole minutes. Choose classifier or regressor for each, and explain which Python dtype alone cannot tell you.', 'Ward codes represent unordered class labels, so classification is appropriate. Whole-minute durations still represent a quantity and support regression. An integer dtype does not identify the scientific task; use the data dictionary and intended interpretation of prediction errors.'),
 'W01':('Training data from a second support centre contain mostly urgent tickets, while deployment includes routine tickets. What would value_counts on y_train reveal, and what would it not establish about deployment?', 'value_counts describes the supplied training-label distribution. It cannot prove that deployment has the same mix or that the sample is representative. Request collection and sampling context, compare relevant independent evidence, and qualify the scope of the model rather than inspecting final rows to redesign it.'),
 'W10':('A colleague sets max_depth=8 before fitting, then reads feature_importances_. Identify the setting and learned attribute, and explain why neither alone tells you whether the model will work on a new workshop.', 'max_depth is a chosen hyperparameter; feature_importances_ is learned during fit. The setting limits complexity and the attribute summarises fitted split reductions. Generalisation to a new workshop needs appropriate validation and population evidence, not just these configuration or fitted-state values.'),
 'R06':('A house-price model includes both floor area in square metres and the same area in square feet. Explain why coefficients may be unstable, propose a feature repair, and state what would decide whether prediction quality changed.', 'The two columns encode the same signal, making individual coefficients non-identifiable or unstable. Keep one unit representation or use a deliberately regularised model. Compare held-out training-fold predictions and errors on matching rows; a changed coefficient does not itself prove a changed predictive relationship.'),
 'R11':('A model predicts exam scores from study time. Rewrite a claim that increasing study time by one hour will cause exactly the fitted coefficient’s increase for every student. What study would support the stronger claim?', 'The coefficient is a modelled association conditional on included features, not an individual causal guarantee. Confounding, measurement and population limits remain. A suitable intervention or defensible causal design would be needed for an effect claim; prediction validation alone cannot supply it.'),
 'C19':('A small three-class dataset has 40 highly correlated measurements and only 12 examples in one class. Explain why fitting a class-specific covariance may fail, and choose a simpler next experiment without consulting final-test scores.', 'A class covariance can be singular or unstable with too few independent observations relative to dimensions. Consider a supported simpler family such as LDA or logistic regression, or a justified training-only representation, and compare using matched training folds. Regularisation choices must be supported by the implementation; do not invent unsupported Playground settings.'),
 'N01':('A laboratory needs one predicted concentration; a recycling centre needs one of four material labels. Choose the neural output task and explain why assigning material codes 0–3 does not turn them into a measured quantity.', 'Concentration uses a regression output in the target units; material labels use classification outputs aligned to classes. Arbitrary numeric category codes do not imply meaningful distances or averages. Select MLPRegressor versus MLPClassifier from the question rather than the storage dtype.'),
 'U01':('A retailer asks for customer segments; another asks whether a customer will cancel next month. Explain why the second needs historical outcomes while the first does not, and why a cluster ID is not automatically a cancellation probability.', 'Segmentation fits similarities in X without y. Cancellation prediction requires a defined outcome, horizon and available inputs, with supervised validation. Cluster identifiers are arbitrary group names; interpreting them as risk probabilities needs separate outcome evidence and an appropriate prediction evaluation.'),
 'U06':('Customers lie along a curved spending continuum with no obvious gaps. K-Means finds four compact groups. Explain how to inspect whether the groups are useful, and why a high score cannot establish four natural customer types.', 'K-Means approximates distance geometry with compact regions and can divide a continuum. Inspect original-unit profiles, sizes, stability and the business purpose. Silhouette or inertia supports a geometric comparison; it does not establish that a unique set of natural customer categories exists.'),
 'U10':('A hierarchy on a sample of urban shops produces three groups. A report claims that every rural shop belongs to those same three types. Rewrite it with a defensible population boundary and name further evidence needed.', 'The hierarchy describes the sampled urban shops under the chosen features, scaling and cut. It does not automatically assign or validate rural shops. Seek representative rural measurements, compare their distributions and assess whether a comparable grouping is useful before generalising the claim.'),
 'P01':('A sensor system needs fewer storage dimensions; an operations team wants named equipment groups. Which request suits PCA and which suits clustering? Explain the difference between an array of component scores and an array of group labels.', 'PCA produces continuous coordinates that combine original measurements and retain selected variation. Clustering produces group assignments under a similarity definition. Compression is not the same as segmentation; neither supplies a future failure target or a supervised prediction guarantee.'),
 'M04':('A model validated on current customers is proposed for applicants rejected under an earlier policy. Name two reasons its evidence may not transfer and describe what a responsible next study must collect.', 'Selection into the observed customer sample and a changed policy can alter both input distributions and outcome relationships. Rejected applicants may lack observed outcomes. Establish the intended population, measurement availability and a defensible data-collection/evaluation design; a familiar feature schema does not establish transportability.'),
}
# These legacy Python transfers retain their useful code contract and add a distinct
# interpretation/decision demand. Written evidence remains explicitly self-reviewed.
REASONING={
 'F02':'A specimen identifier is added at intake and its confirmed class later. Which belongs in X, and why does a numeric identifier not automatically become a legitimate measurement?',
 'F04':'Explain why selecting the training schema is safer than passing every incoming column. What would you do if a required measurement were absent?',
 'F07':'Candy rows describe products, not time. Explain when this random split is defensible and how your design would change for repeated measurements of the same product.',
 'F09':'Suppose a class occurs only twice. Explain why stratification cannot create enough independent evidence for five-fold class evaluation.',
 'W03':'If temperature units change in incoming data, can reusing the old scaler fix the measurement mismatch? Explain the difference between consistent units and learned scaling.',
 'W04':'Suppose the next Penguin arrives from an unseen island. Explain the all-zero encoded block and why it is preferable to fitting the encoder again on test rows.',
 'W05':'Year is encoded here as a category. Explain how a future-year prediction question could instead require a chronological evaluation, even though the code runs.',
 'W06':'Explain which objects get refitted in each validation fold and how a pipeline prevents the training-validation rows from sharing learned preparation.',
 'W07':'Suppose missingness itself signals a change in data collection. Explain what median filling can repair and what evidence about that change is still needed.',
 'W08':'Explain why these stratified folds are appropriate for independent class examples but not for successive observations of the same specimen.',
 'W12':'Choose one kind of confusion from the returned errors. Explain a training-only investigation and why the final test cannot become your debugging set.',
 'R02':'A new population has a shifted average. Explain why its evaluation-mean R² reference differs from a deployable constant learned on training outcomes.',
 'R07':'Explain which new interaction term allows the distance effect to depend on weight. What validation evidence is needed before retaining that term?',
 'R09':'Explain why this tree does not require the numerical scaling used by neighbour models, and why a deep tree may still fail to generalise to unfamiliar candies.',
 'C01':'No C predictions were made. Explain what the empty prediction column reveals that a matrix dropping class C would conceal.',
 'C02':'If missing class B becomes more costly, which reported error rate deserves attention? Explain why changing the reporting priority is not proof the model improved.',
 'C03':'Explain how the dummy’s minority-class F1 changes your interpretation of accuracy. What evidence would make a more complex model worth using?',
 'C04':'If the application can defer uncertain cases, explain what information argmax discards and how a deferral rule should be validated.',
 'C05':'Explain why each coefficient row must be paired with its fitted class name; what could go wrong if you assume alphabetical order externally?',
 'C06':'Island may be unavailable at a future prediction site. Use the ablation evidence to discuss whether the measurements-only model better matches that intended use.',
 'C13':'An integer field is actually an unordered category code. Explain why a dtype-based numeric interval rule could be scientifically inappropriate despite running successfully.',
 'C17':'Explain why probabilities must be paired with fitted class labels and why their summing to one does not prove calibration.',
 'N04':'The transformed target has a standard deviation near one. Explain why its RMSE cannot be quoted as minutes without returning predictions to original units.',
 'U03':'A stakeholder names a sugar/price group “healthy”. Explain what the measured profile supports and which unmeasured variables make that label unjustified.',
 'P02':'A new batch arrives with the same measurement names but different units. Explain why calling transform cannot repair the schema’s scientific meaning.',
 'P04':'A diagnosis task follows the 90% rule. Explain why retaining variance alone cannot choose the best supervised representation; where must PCA fit during validation?',
 'P05':'Explain why losing the score table’s original row index could silently mislabel a later plot coloured by an external label.',
}

def append(content, short):
    if short in ADDITIONS:
        task,answer=ADDITIONS[short]
        content['exercises'].append(reflect(task,answer))

def enrich(registry):
    for c in registry['cards']:
        short=c['id'].removeprefix('ML-')
        if short in REASONING:
            e=c['exercises'][-1]
            e['reasoningPrompt']=REASONING[short]
            e['task']+=' Then explain: '+REASONING[short]
    return registry
